In [1]:
import pandas as pd

df = pd.DataFrame()

In [2]:
input_ = pd.read_excel('./model_1.xlsx',
                       header=0,
                       dtype=str).fillna('')

print('总数量：' + str(len(input_)))
input_['Model_Id'].tolist()

总数量：608

['41',
 '8247',
 '5443',
 '4628',
 '4038',
 '3467',
 '3442',
 '1806',
 '490',
 '371',
 '366',
 '362',
 '259',
 '255',
 '189',
 '3866',
 '181',
 '184',
 '45',
 '50',
 '56',
 '59',
 '63',
 '55',
 '69',
 '70',
 '74',
 '75',
 '80',
 '64',
 '85',
 '1934',
 '1942',
 '2030',
 '2031',
 '3949',
 '4400',
 '1929',
 '4426',
 '3486',
 '1928',
 '1527',
 '1535',
 '1533',
 '1532',
 '1531',
 '1530',
 '1526',
 '1523',
 '1520',
 '4445',
 '1536',
 '7545',
 '1518',
 '1519',
 '1175',
 '4742',
 '4054',
 '3546',
 '3475',
 '1885',
 '1327',
 '1183',
 '1306',
 '4581',
 '3973',
 '1244',
 '1233',
 '90',
 '512',
 '1614',
 '3468',
 '438',
 '3485',
 '258',
 '253',
 '202',
 '194',
 '176',
 '13',
 '78',
 '36',
 '31',
 '30',
 '19',
 '6',
 '1',
 '84',
 '26',
 '456',
 '286',
 '486',
 '322',
 '7590',
 '3969',
 '2044',
 '2024',
 '2023',
 '2022',
 '1776',
 '1751',
 '1750',
 '2043',
 '1606',
 '1603',
 '1483',
 '444',
 '373',
 '1690',
 '368',
 '335',
 '330',
 '4645',
 '347',
 '342',
 '338',
 '3445',
 '552',
 '548',
 '543',
 '538',
 '534',
 '524',
 '96',
 '18',
 '12',
 '3385',
 '3577',
 '52',
 '24',
 '570',
 '1230',
 '1551',
 '5393',
 '3943',
 '3889',
 '3888',
 '1630',
 '1629',
 '1628',
 '1627',
 '1626',
 '1598',
 '455',
 '4003',
 '30',
 '31',
 '1940',
 '3485',
 '3468',
 '25',
 '438',
 '258',
 '253',
 '202',
 '194',
 '176',
 '172',
 '84',
 '78',
 '36',
 '19',
 '10',
 '13',
 '1',
 '26',
 '6',
 '1551',
 '5393',
 '3943',
 '4003',
 '9531',
 '9532',
 '39',
 '96',
 '5455',
 '4947',
 '4874',
 '4095',
 '106',
 '3575',
 '38735',
 '3907',
 '3889',
 '1629',
 '1630',
 '4171',
 '4170',
 '4169',
 '4167',
 '3410',
 '1305',
 '1304',
 '3412',
 '3512',
 '3513',
 '3411',
 '1303',
 '1240',
 '1232',
 '1239',
 '3403',
 '1232',
 '1239',
 '1240',
 '3973',
 '5400',
 '6154',
 '6155',
 '3890',
 '330',
 '326',
 '1688',
 '79',
 '335',
 '322',
 '3444',
 '344',
 '373',
 '368',
 '1686',
 '1685',
 '1684',
 '1687',
 '514',
 '474',
 '469',
 '518',
 '3958',
 '790',
 '9532',
 '9531',
 '52',
 '3485',
 '438',
 '253',
 '1551',
 '5393',
 '4003',
 '1483',
 '1751',
 '2024',
 '2043',
 '2044',
 '3969',
 '7590',
 '4508',
 '2016',
 '2017',
 '3511',
 '4503',
 '526',
 '470',
 '467',
 '461',
 '450',
 '447',
 '279',
 '199',
 '162',
 '3459',
 '89',
 '44',
 '3456',
 '27',
 '3970',
 '3458',
 '1682',
 '4700',
 '4699',
 '3959',
 '3492',
 '1681',
 '1643',
 '4701',
 '355',
 '351',
 '346',
 '341',
 '317',
 '313',
 '360',
 '10644',
 '10643',
 '10642',
 '10641',
 '9520',
 '9522',
 '48',
 '1',
 '6',
 '10',
 '14',
 '4554',
 '1502',
 '1500',
 '433',
 '26',
 '84',
 '78',
 '53',
 '31',
 '194',
 '165',
 '1903',
 '1992',
 '93',
 '409',
 '569',
 '38756',
 '398',
 '4076',
 '1319',
 '1480',
 '3994',
 '4074',
 '4075',
 '426',
 '3886',
 '39690',
 '4004',
 '3887',
 '3885',
 '423',
 '1996',
 '210',
 '214',
 '270',
 '275',
 '403',
 '405',
 '1482',
 '408',
 '412',
 '415',
 '195',
 '419',
 '431',
 '436',
 '440',
 '488',
 '493',
 '497',
 '500',
 '505',
 '3439',
 '507',
 '427',
 '510',
 '1614',
 '7',
 '1993',
 '1621',
 '1620',
 '1616',
 '90',
 '1447',
 '425',
 '3521',
 '3522',
 '4778',
 '1888',
 '1890',
 '1594',
 '3940',
 '4562',
 '4773',
 '4774',
 '3506',
 '5',
 '1703',
 '1964',
 '1965',
 '1966',
 '1702',
 '3392',
 '37943',
 '2042',
 '3433',
 '4841',
 '4990',
 '4998',
 '8610',
 '9983',
 '1540',
 '1559',
 '273',
 '264',
 '3921',
 '4898',
 '5615',
 '8784',
 '9836',
 '9967',
 '3555',
 '269',
 '790',
 '29',
 '35',
 '552',
 '543',
 '9',
 '4',
 '548',
 '3445',
 '571',
 '570',
 '557',
 '236',
 '1636',
 '3379',
 '3380',
 '1637',
 '3378',
 '9532',
 '9530',
 '9528',
 '9533',
 '9535',
 '9536',
 '9531',
 '11611',
 '36543',
 '40531',
 '4955',
 '5143',
 '6724',
 '40796',
 '11282',
 '10459',
 '10253',
 '41359',
 '41360',
 '5111',
 '5378',
 '5431',
 '6236',
 '10734',
 '11279',
 '11484',
 '38536',
 '38537',
 '40534',
 '40535',
 '36512',
 '11195',
 '11196',
 '38149',
 '38190',
 '10735',
 '4991',
 '5379',
 '7873',
 '9118',
 '9158',
 '9710',
 '10585',
 '11221',
 '11878',
 '40179',
 '40210',
 '41185',
 '404',
 '39570',
 '3399',
 '15',
 '5055',
 '4199',
 '2047',
 '4589',
 '2046',
 '1242',
 '4582',
 '1241',
 '3436',
 '1830',
 '314',
 '232',
 '75',
 '70',
 '68',
 '54',
 '4433',
 '4411',
 '2032',
 '1938',
 '4439',
 '1933',
 '426',
 '398',
 '1319',
 '1480',
 '3994',
 '4074',
 '4075',
 '4076',
 '38756',
 '4004',
 '1305',
 '1304',
 '371',
 '490',
 '366',
 '184',
 '181',
 '1806',
 '80',
 '74',
 '69',
 '63',
 '376',
 '85',
 '380',
 '3440',
 '388',
 '3442',
 '3866',
 '4038',
 '5443',
 '1830',
 '4439',
 '1518',
 '3979',
 '1519',
 '1520',
 '1522',
 '1523',
 '1531',
 '1532',
 '1536',
 '1928',
 '2030',
 '2031',
 '1521',
 '4440',
 '3486',
 '4400',
 '4663',
 '2041',
 '3505',
 '3906',
 '3909',
 '4662',
 '2014',
 '4664',
 '2039',
 '1749',
 '1313',
 '2040',
 '3378',
 '3380',
 '3379',
 '1547',
 '4348',
 '40151',
 '88',
 '316',
 '3389',
 '483',
 '339',
 '312',
 '334',
 '3448',
 '12',
 '18',
 '24',
 '52',
 '106',
 '118',
 '570',
 '3907',
 '1604',
 '1466',
 '1465',
 '1464',
 '1463',
 '411',
 '358',
 '372',
 '367',
 '1517',
 '349',
 '378',
 '1572',
 '1467',
 '1605',
 '3388',
 '3449',
 '3960',
 '3961',
 '4051',
 '4710',
 '4711',
 '10465',
 '147',
 '12773',
 '1846',
 '4131',
 '4132',
 '5617',
 '5618',
 '7380',
 '7381',
 '7382',
 '8929',
 '37944',
 '4130',
 '12774']

In [3]:
import os

In [4]:
list_file = list(os.walk('./engine'))[0][2]
if '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
if '0.null.txt' in list_file:
    list_file.remove('0.null.txt')
    
list_file.sort()
    
len(list_file)

608

In [5]:
from tqdm import tqdm
import json

In [6]:
for a in tqdm(range(len(list_file)), desc='Progress', ncols=77):
    with open('./engine/' + list_file[a], 'r', encoding='UTF-8') as file:
        resp = file.read()
        
    # = = = = = = = = = = = = = = =
    
    json_data = json.loads(resp)
    
    # = = = = = = = = = = = = = = =
    
    vehicle_2 = '\n'.join([input_.loc[int(list_file[a].replace('.txt', ''))-1, 'Vehicle_1'] + ' ' + engine['title'].strip() for engine in json_data['vehicles']])

    # = = = = = = = = = = = = = = =
    
    df_temp = pd.DataFrame([{'No.': int(list_file[a].replace('.txt', '')),
                             'Product_Id': input_.loc[int(list_file[a].replace('.txt', ''))-1, 'Product_Id'],
                             'Vehicle_2': vehicle_2}])

    df = pd.concat([df, df_temp], ignore_index=True).fillna('')
    
# = = = = = = = = = = = = = = =

df = df.drop_duplicates(ignore_index=True)
df = df.sort_values(by=['No.'], ascending=[True]).reset_index(drop=True)

df

Progress: 100%|██████████████████████████| 608/608 [00:00<00:00, 1671.92it/s]

     No. Product_Id                                          Vehicle_2
0      1    1363314  OPEL Kadett C Caravan (Baujahr 08.1973 - 07.19...
1      2    1363314  OPEL Corsa B Caravan (S93) (Baujahr 01.1999 - ...
2      3    1363314  OPEL Kadett D Limousine (Baujahr 08.1979 - 08....
3      4    1363314  OPEL Corsa B Kastenwagen (S93) (Baujahr 08.199...
4      5    1363314  OPEL Kadett E Kastenwagen (T85) (Baujahr 08.19...
..   ...        ...                                                ...
603  604    1362261  LADA Kalina Kombi (1117) (Baujahr 10.2004 - 12...
604  605    1362261  LADA Priora Kombi (2171) (Baujahr 10.2009 - 12...
605  606    1362261  LADA Granta Liftback (2191) (Baujahr 08.2014 -...
606  607    1362261  LADA 110 (2110) (Baujahr 01.1995 - 12.2012) 1....
607  608    1362261  LADA Kalina II Schrägheck (2192) (Baujahr 06.2...

[608 rows x 3 columns]

In [7]:
df = df[['Product_Id', 'Vehicle_2']]
df = df.groupby('Product_Id', as_index=False).agg({'Vehicle_2': '\n'.join})
df.to_excel('./engine.xlsx', index=False)

df

   Product_Id                                          Vehicle_2
0     1362261  LADA Granta (2190) (Baujahr 10.2011 - ...) 1.6...
1     1362271  KIA Pride Schrägheck (DA) (Baujahr 01.1990 - 1...
2     1362323  FIAT Tipo Schrägheck (160) (Baujahr 07.1987 - ...
3     1362345  FORD Escort Express '91 (AVF) (Baujahr 07.1990...
4     1362368  FORD Transit Mk4 Bus (VE83) (Baujahr 06.1994 -...
5     1362383  ALFA ROMEO 90 (162) (Baujahr 10.1984 - 07.1987...
6     1362409  DAIHATSU Cuore III (L201) (Baujahr 08.1990 - 0...
7     1362413  DAEWOO Tico (Baujahr 02.1995 - 12.2000) 0.8, B...
8     1362433  SUZUKI SJ 413 (OS) (Baujahr 09.1984 - 03.1991)...
9     1362479  DAEWOO Lanos Limousine (Baujahr 02.1997 - ...)...
10    1362480  DAEWOO Nexia I Limousine (N100) (Baujahr 02.19...
11    1362570  SKODA Favorit Forman (785) (Baujahr 06.1988 - ...
12    1362635  AUDI A4 B5 Avant (8D5) (Baujahr 11.1994 - 09.2...
13    1362644  FIAT Strada Pickup (178) (Baujahr 02.1998 - .....
14    1362666  CITROËN Xsara Kombi (N2) (Baujahr 10.1997 - 03...
15    1362755  AUDI A3 Cabrio (8V7, 8VE) (Baujahr 10.2013 - ....
16    1362802  SUZUKI Swift Cabrio (SF413) (Baujahr 09.1991 -...
17    1362803  SUZUKI Swift II Schrägheck (EA, MA) (Baujahr 0...
18    1362838  HYUNDAI Pony Kombi (Baujahr 02.1978 - 06.1986)...
19    1362842  CHEVROLET Matiz (M200, M250) (Baujahr 03.2005 ...
20    1362913  FORD Taunus Turnier (GBNK) (Baujahr 08.1970 - ...
21    1362921  OPEL Commodore C Limousine (Baujahr 08.1978 - ...
22    1362923  FORD Escort Mk3 Kombi (AWA) (Baujahr 09.1980 -...
23    1362925  VW Kaefer (Baujahr 12.1947 - 08.2003) 1200 1.2...
24    1362932  AUDI 100 C3 Avant (44, 44Q) (Baujahr 08.1982 -...
25    1363252  MERCEDES-BENZ 190 (W201) (Baujahr 10.1982 - 08...
26    1363312  MERCEDES-BENZ E-Klasse Coupe (C124) (Baujahr 0...
27    1363314  OPEL Kadett C Caravan (Baujahr 08.1973 - 07.19...
28      15777  FIAT 238-Serie Bus (Baujahr 09.1966 - 06.1982)...
29      15778  FIAT 238-Serie Bus (Baujahr 09.1966 - 06.1982)...
30      15779  MERCEDES-BENZ Sprinter 4-T Kastenwagen (W904) ...
31      15808  RENAULT TRUCKS B Pritsche/Fahrgestell (Baujahr...
32      15809  RENAULT TRUCKS B Kasten/Kombi (Baujahr 01.1983...
33      15811  RENAULT TRUCKS B Pritsche/Fahrgestell (Baujahr...
34      15842  LDV 400 Bus (Baujahr 11.1995 - 10.1998) 2.5 TD...
35      16141  IVECO Daily II Kipper (Baujahr 01.1989 - 05.19...
36      16142  CITROËN C25 Bus (Baujahr 07.1981 - 02.1994) 1....
37      16143  AUDI A6 C4 Avant (4A5) (Baujahr 06.1994 - 12.1...
38      16144  MERCEDES-BENZ SL Cabrio (R129) (Baujahr 03.198...
39      16145  MERCEDES-BENZ S-Klasse Limousine (W126) (Bauja...
40    7275104  AUDI 100 C1 Coupe (Baujahr 01.1970 - 12.1976) ...