In [1]:
param_make = 'ALFA ROMEO'

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('./' + param_make + '/7.part.xlsx',
                   header=0,
                   dtype=str).fillna('')

list_type_code = df['Type_Code'].tolist()
list_part_key = df['Part_Key'].tolist()

print('总数量：' + str(len(list_part_key)))
list_part_key

总数量：17290

['13651017',
 '10411221',
 '10411241',
 '10411245',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '6576040',
 '13643225',
 '8936488',
 '6839008',
 '6839012',
 '14266269',
 '14061237',
 '12974733',
 '10410961',
 '13651145',
 '14053393',
 '14053397',
 '10410957',
 '13651017',
 '10411221',
 '10411241',
 '10411245',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '13651141',
 '13651193',
 '13651405',
 '14266913',
 '14266341',
 '13640421',
 '10410961',
 '13651145',
 '14053393',
 '14053397',
 '10410957',
 '13651017',
 '10411221',
 '10411241',
 '10411245',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '6576040',
 '13643225',
 '6839008',
 '6839012',
 '1040475',
 '4768884',
 '14266269',
 '11963309',
 '14061237',
 '14005821',
 '12974733',
 '10410961',
 '13651145',
 '14053393',
 '14053397',
 '10410957',
 '13651017',
 '10411221',
 '10411241',
 '10411245',
 '13651141',
 '13651193',
 '13651405',
 '14266913',
 '14266341',
 '13640421',
 '14061237',
 '14005821',
 '10410961',
 '13651145',
 '14053393',
 '14053397',
 '10410957',
 '14266933',
 '15244989',
 '14266285',
 '8749600',
 '7680312',
 '13924853',
 '12789901',
 '11727065',
 '12976853',
 '12976857',
 '13651017',
 '14122185',
 '14746589',
 '11908169',
 '11565865',
 '11652621',
 '11577017',
 '11664301',
 '11579573',
 '11666981',
 '9145444',
 '8745448',
 '9145520',
 '8748404',
 '11909541',
 '11910969',
 '12973389',
 '12973397',
 '10411221',
 '10411241',
 '10411245',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '8878456',
 '11749965',
 '8879272',
 '14022845',
 '11378617',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '12957052',
 '6319518',
 '12957056',
 '12957060',
 '6319527',
 '15106485',
 '15106489',
 '6319530',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '6319488',
 '8142808',
 '11677245',
 '6318786',
 '6318789',
 '6318792',
 '12956940',
 '9101784',
 '9101792',
 '8934984',
 '6318603',
 '6319152',
 '5921868',
 '1311223',
 '2922678',
 '4366809',
 '11192617',
 '8205252',
 '999460',
 '1888140',
 '1385649',
 '6576040',
 '13643225',
 '11123105',
 '3852705',
 '13771941',
 '4373703',
 '6839008',
 '6839012',
 '1040475',
 '4768884',
 '4971873',
 '12912309',
 '12605509',
 '11960321',
 '14266269',
 '11963309',
 '15027013',
 '14065316',
 '13610629',
 '11041008',
 '14911121',
 '14061237',
 '14266669',
 '14005821',
 '12974733',
 '14901805',
 '10865736',
 '10865748',
 '10410961',
 '13651145',
 '14053393',
 '14053397',
 '10410957',
 '13944689',
 '10572160',
 '2992533',
 '3972015',
 '11169301',
 '1874608',
 '1874604',
 '2866809',
 '2866836',
 '14759113',
 '11105957',
 '11105977',
 '7504904',
 '1021519',
 '1874586',
 '1874568',
 '5755986',
 '4004955',
 '4005009',
 '4004991',
 '4004985',
 '14832649',
 '14832669',
 '14832849',
 '13924853',
 '12789901',
 '11727065',
 '12976853',
 '12976857',
 '13651017',
 '14122185',
 '14746589',
 '11908169',
 '12748773',
 '12748861',
 '11565865',
 '11652621',
 '11576985',
 '11577017',
 '11664301',
 '11579573',
 '11666981',
 '4504539',
 '8482328',
 '8172332',
 '8482400',
 '11507393',
 '11507409',
 '11909541',
 '11909545',
 '11910969',
 '12973389',
 '12973397',
 '10411221',
 '10411241',
 '10411245',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '8878456',
 '11749965',
 '8879272',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '12957052',
 '6319518',
 '12957056',
 '12957060',
 '6319527',
 '15106485',
 '15106489',
 '6319530',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '6319488',
 '8142808',
 '11677245',
 '6318786',
 '6318789',
 '6318792',
 '12956940',
 '9101784',
 '9101792',
 '8934984',
 '6318603',
 '6319152',
 '10933364',
 '10933328',
 '10933332',
 '13651193',
 '13651405',
 '14266913',
 '4971873',
 '12864785',
 '12605913',
 '14266341',
 '13640421',
 '14065316',
 '13610629',
 '11041008',
 '14911121',
 '14061237',
 '11963121',
 '14266669',
 '14005821',
 '13238297',
 '13011913',
 '13011917',
 '13011921',
 '14901805',
 '10933200',
 '10933204',
 '10865736',
 '10865748',
 '10410961',
 '10410957',
 '13944689',
 '10572160',
 '2992533',
 '3972015',
 '11169301',
 '1874608',
 '1874604',
 '2866809',
 '2866836',
 '14759113',
 '11105957',
 '11105977',
 '7504904',
 '1021519',
 '1874586',
 '1874568',
 '5755986',
 '4004955',
 '4005009',
 '4004991',
 '4004985',
 '14832649',
 '14832669',
 '14832849',
 '7680312',
 '9855212',
 '11266968',
 '11727065',
 '12976853',
 '12976857',
 '13651017',
 '11910969',
 '12973389',
 '12973397',
 '10411221',
 '10411241',
 '10411245',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '8878456',
 '11749965',
 '8879272',
 '6319551',
 '12957052',
 '6319518',
 '12957056',
 '12957060',
 '6319527',
 '15106485',
 '15106489',
 '6319530',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '6319488',
 '12956929',
 '6319629',
 '12957092',
 '12957096',
 '6319638',
 '6319641',
 '11677245',
 '6318786',
 '6318789',
 '6318792',
 '12956940',
 '9101784',
 '9101792',
 '8934984',
 '6318603',
 '6319152',
 '12242701',
 '5921868',
 '1311223',
 '2922678',
 '4366809',
 '11192617',
 '8205252',
 '999460',
 '1888140',
 '1385649',
 '6576040',
 '13643225',
 '11123105',
 '3852705',
 '13771941',
 '4373703',
 '6839008',
 '6839012',
 '1040475',
 '4768884',
 '4971873',
 '12912309',
 '12605509',
 '11960321',
 '14266269',
 '11963309',
 '15027013',
 '14065316',
 '15105749',
 '11041008',
 '14911121',
 '14061237',
 '14266669',
 '14005821',
 '12974733',
 '14901805',
 '10865736',
 '10865748',
 '13944689',
 '10572160',
 '2992533',
 '3972015',
 '11169301',
 '1874608',
 '1874620',
 '2866809',
 '2866821',
 '11105957',
 '11105985',
 '13060217',
 '7504904',
 '1021522',
 '1874586',
 '1874584',
 '4004955',
 '4004973',
 '5756001',
 '4004991',
 '4004940',
 '14832649',
 '14832677',
 '14832849',
 '14832877',
 '8115760',
 '9855212',
 '11727065',
 '12976853',
 '12976857',
 '13651017',
 '11909541',
 '11909545',
 '12973389',
 '12973397',
 '10411221',
 '10411241',
 '10411245',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '8878456',
 '11749965',
 '8879272',
 '6319551',
 '12957052',
 '6319518',
 '12957056',
 '12957060',
 '6319527',
 '15106485',
 '15106489',
 '6319530',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '6319488',
 '12956929',
 '6319629',
 '12957092',
 '12957096',
 '6319638',
 '6319641',
 '11677245',
 '6318786',
 '6318789',
 '6318792',
 '12956940',
 '9101784',
 '9101792',
 '8934984',
 '6318603',
 '6319152',
 '12242701',
 '10933364',
 '10933328',
 '10933332',
 '13651193',
 '13651405',
 '14266913',
 '4971873',
 '12605913',
 '14266341',
 '13640421',
 '14065316',
 '11041008',
 '14911121',
 '14061237',
 '11963121',
 '14266669',
 '14005821',
 '13011901',
 '13011905',
 '13011909',
 '14901805',
 '10933200',
 '10933204',
 '10865736',
 '10865748',
 '10410961',
 '10410957',
 '13944689',
 '10572160',
 '2992533',
 '3972015',
 '11169301',
 '1874608',
 '1874620',
 '2866809',
 '2866821',
 '11105957',
 '11105985',
 '13060217',
 '7504904',
 '1021522',
 '1874586',
 '1874584',
 '4004955',
 '4004973',
 '5756001',
 '4004991',
 '4004940',
 '14832649',
 '14832677',
 '14832849',
 '14832877',
 '8115760',
 '347535',
 '960513',
 '4260',
 '3001647',
 '15096973',
 '12785577',
 '13924853',
 '13978009',
 '12789901',
 '11727065',
 '12976853',
 '12976857',
 '13651017',
 '14122185',
 '14746589',
 '11908169',
 '11565865',
 '11652621',
 '11577017',
 '11664301',
 '11579573',
 '11666981',
 '9145444',
 '8745448',
 '9145520',
 '8748404',
 '11909541',
 '11910969',
 '14907205',
 '11585193',
 '11594121',
 '11603549',
 '11603553',
 '11621645',
 '11621649',
 '12973389',
 '12973397',
 '10411221',
 '10411241',
 '10411245',
 '11777985',
 '14808705',
 '13047201',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '8878456',
 '11749965',
 '8879272',
 '14001597',
 '14831133',
 '14022845',
 '11378617',
 '14830581',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '12957040',
 '10144177',
 '12957052',
 '6319518',
 '12957056',
 '12957060',
 '6319527',
 '15106485',
 '15106489',
 '6319530',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '6319488',
 '8142808',
 '11677245',
 '6318786',
 '6318789',
 '6318792',
 '12956940',
 '9101784',
 '9101792',
 '8934984',
 '6318603',
 '6319152',
 '12393153',
 '13619797',
 '13619801',
 '14925997',
 '14926001',
 '12173877',
 '14967345',
 '5921868',
 '1311223',
 '2922678',
 '1518516',
 '4366809',
 '11192617',
 '8205252',
 '999460',
 '1888140',
 '1385649',
 '6576040',
 '13643225',
 '6365244',
 '11123105',
 '3852705',
 '9662768',
 '13771941',
 '4373703',
 '6839008',
 '6839012',
 '1040475',
 '4768884',
 '4971873',
 '13046449',
 '12912309',
 '12605509',
 '11960321',
 '14266269',
 '11963309',
 '15027013',
 '7677652',
 '14065316',
 '13610629',
 '11041008',
 '14911121',
 '14061237',
 '14266669',
 '14005821',
 '10055076',
 '2061308',
 '11398873',
 '13643405',
 '13642177',
 '12974733',
 '8968732',
 '8968736',
 '8968740',
 '8968744',
 '8968748',
 '8968752',
 '12340649',
 '12340653',
 '12353785',
 '12353789',
 '14901805',
 '14696265',
 '13932401',
 '12283909',
 '12284789',
 '13932205',
 '10865736',
 '10865748',
 '15206737',
 '10410961',
 '10410957',
 '15186905',
 '15186909',
 '12306313',
 '15104381',
 '15104385',
 '8148896',
 '14873077',
 '10931700',
 '13944689',
 '10572160',
 '2992533',
 '3972015',
 '11169301',
 '1874608',
 '1874604',
 '2866809',
 '2866836',
 '14759113',
 '11105957',
 '11105977',
 '7504904',
 '1021519',
 '1874586',
 '1874568',
 '5755986',
 '4004955',
 '4005009',
 '4004991',
 '4004985',
 '14832649',
 '14832669',
 '14832849',
 '13924853',
 '13978009',
 '12789901',
 '11727065',
 '12976853',
 '12976857',
 '13651017',
 '14122185',
 '14746589',
 '11908169',
 '12748773',
 '12748861',
 '11576985',
 '4504539',
 '8482328',
 '8172332',
 '8482400',
 '11507393',
 '11507409',
 '11909545',
 '11600165',
 '11601009',
 '11644629',
 '12973389',
 '12973397',
 '10411221',
 '10411241',
 '10411245',
 '14309481',
 '13047201',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '8878456',
 '11749965',
 '8879272',
 '14001597',
 '14992821',
 '15100421',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '12957040',
 '10144177',
 '12957052',
 '6319518',
 '12957056',
 '12957060',
 '6319527',
 '15106485',
 '15106489',
 '6319530',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 '6319488',
 '8142808',
 '11677245',
 '6318786',
 '6318789',
 '6318792',
 '12956940',
 '9101784',
 '9101792',
 '8934984',
 '6318603',
 '6319152',
 '10933364',
 '10933328',
 '10933332',
 '13651193',
 '13651405',
 '14266913',
 '4971873',
 '12864785',
 '12605913',
 '14266341',
 '13640421',
 '7677652',
 '14065316',
 '13610629',
 '11041008',
 '14911121',
 '14061237',
 '11963121',
 '14266669',
 '14005821',
 '14867933',
 '12599185',
 '13238297',
 '8968732',
 '8968736',
 '8968740',
 '8968744',
 '8968748',
 '8968752',
 '13011913',
 '13011917',
 '13011921',
 '12340649',
 '12340653',
 '12353785',
 '12353789',
 '14901805',
 '12639305',
 '14696265',
 '13932405',
 '15231885',
 '12284793',
 '13932661',
 '10933200',
 '10933204',
 '10865736',
 '10865748',
 '15206737',
 '10410961',
 '10410957',
 '15186905',
 '15186909',
 '12306313',
 '15104381',
 '15104385',
 '8148896',
 '14873077',
 '10931700',
 '13944689',
 '10572160',
 '2992533',
 '3972015',
 '11169301',
 '1874608',
 '1874604',
 '2866809',
 '2866836',
 '14759113',
 '11105957',
 '11105977',
 '7504904',
 '1021519',
 '1874586',
 '1874568',
 '5755986',
 '4004955',
 '4005009',
 '4004991',
 '4004985',
 '14832649',
 '14832669',
 '14832849',
 '347535',
 '7680312',
 '960513',
 '4260',
 '3001647',
 '12785577',
 '14779269',
 '12267869',
 '12270925',
 '13924861',
 '9855212',
 '11266968',
 '11727065',
 '12976853',
 '12976857',
 '13651017',
 '10459608',
 '13976389',
 '9143384',
 '13976893',
 '14728489',
 '14736709',
 '2046112',
 '9158372',
 '10623540',
 '11909541',
 '11910969',
 '10571844',
 '14907205',
 '11585193',
 '11594121',
 '11603549',
 '11603553',
 '11621645',
 '11621649',
 '10622780',
 '10622784',
 '12973389',
 '12973397',
 '10411221',
 '10411241',
 '10411245',
 '11777985',
 '14808705',
 '13047201',
 '13651033',
 '13651221',
 '12803669',
 '10411169',
 '8878456',
 '11749965',
 '8879272',
 '14001597',
 '14831133',
 '14022845',
 '11378617',
 '14830581',
 '6319551',
 '14872633',
 '12957040',
 '10144177',
 '12957052',
 '6319518',
 '12957056',
 '12957060',
 '6319527',
 '15106485',
 '15106489',
 '6319530',
 '12956940',
 '4222461',
 '9101784',
 '6318882',
 '6318888',
 '9101792',
 '8934984',
 ...]

In [4]:
df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [5]:
from urllib.parse import quote
import requests
import json

In [6]:
i = 0

type_code = list_type_code[0]
part_key = list_part_key[0]

if part_key == 'Nan':
    print('fuck')

data = 'func=getbuyersguide&payload=' + quote('{"partData":{"listing_data_essential":{"parttype":"') + type_code + quote('","partkey":"') + part_key + quote('"}}}') + '&api_json_request=1&sctchecked=1&scbeenloaded=true&curCartGroupID='

resp = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                     data=data,
                     headers={'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}).text

resp = json.loads(resp)

resp

{'buyersguidepieces': {'body': '<div class="buyersguide-nested"><div style="padding: .5em;"><div>Results may be incomplete due to size of result set</div><table class="nobmp" style="width: 100%;"><tr><td class="altrow-a-0">ACURA</td><td class="altrow-a-0">1996-2022</td></tr><tr><td class="altrow-a-1">ALFA ROMEO</td><td class="altrow-a-1">2018-2023</td></tr><tr><td class="altrow-a-0">BMW</td><td class="altrow-a-0">1986-2014</td></tr><tr><td class="altrow-a-1">BUICK</td><td class="altrow-a-1">1993-2020</td></tr><tr><td class="altrow-a-0">CADILLAC</td><td class="altrow-a-0">1996-2022</td></tr><tr><td class="altrow-a-1">CHEVROLET</td><td class="altrow-a-1">1985-2024</td></tr><tr><td class="altrow-a-0">CHRYSLER</td><td class="altrow-a-0">1988-2023</td></tr><tr><td class="altrow-a-1">DAEWOO</td><td class="altrow-a-1">1999-2000</td></tr><tr><td class="altrow-a-0">DODGE</td><td class="altrow-a-0">1989-2023</td></tr><tr><td class="altrow-a-1">FERRARI</td><td class="altrow-a-1">1990-2016</td></tr><tr><td class="altrow-a-0">FIAT</td><td class="altrow-a-0">2012-2020</td></tr><tr><td class="altrow-a-1">FORD</td><td class="altrow-a-1">1993-2013</td></tr><tr><td class="altrow-a-0">GENESIS</td><td class="altrow-a-0">2018-2023</td></tr><tr><td class="altrow-a-1">GMC</td><td class="altrow-a-1">1994-2023</td></tr><tr><td class="altrow-a-0">HONDA</td><td class="altrow-a-0">1985-2023</td></tr><tr><td class="altrow-a-1">HUMMER</td><td class="altrow-a-1">2004-2005</td></tr><tr><td class="altrow-a-0">HYUNDAI</td><td class="altrow-a-0">2000-2023</td></tr><tr><td class="altrow-a-1">INFINITI</td><td class="altrow-a-1">1992-2022</td></tr><tr><td class="altrow-a-0">ISUZU</td><td class="altrow-a-0">1988-1997</td></tr><tr><td class="altrow-a-1">JAGUAR</td><td class="altrow-a-1">1992-2008</td></tr><tr><td class="altrow-a-0">JEEP</td><td class="altrow-a-0">1987-2023</td></tr><tr><td class="altrow-a-1">KIA</td><td class="altrow-a-1">2002-2024</td></tr><tr><td class="altrow-a-0">LAMBORGHINI</td><td class="altrow-a-0">1991-1992</td></tr><tr><td class="altrow-a-1">LAND ROVER</td><td class="altrow-a-1">1995-2007</td></tr><tr><td class="altrow-a-0">LEXUS</td><td class="altrow-a-0">1990-2023</td></tr><tr><td class="altrow-a-1">LINCOLN</td><td class="altrow-a-1">2000-2014</td></tr><tr><td class="altrow-a-0">LOTUS</td><td class="altrow-a-0">1990-2017</td></tr><tr><td class="altrow-a-1">MASERATI</td><td class="altrow-a-1">2003-2017</td></tr><tr><td class="altrow-a-0">MAZDA</td><td class="altrow-a-0">1991-2023</td></tr><tr><td class="altrow-a-1">MERCURY</td><td class="altrow-a-1">2004-2011</td></tr><tr><td class="altrow-a-0">MINI</td><td class="altrow-a-0">2007-2008</td></tr><tr><td class="altrow-a-1">MITSUBISHI</td><td class="altrow-a-1">1991-2023</td></tr><tr><td class="altrow-a-0">NISSAN</td><td class="altrow-a-0">1991-2023</td></tr><tr><td class="altrow-a-1">OLDSMOBILE</td><td class="altrow-a-1">1985-2003</td></tr><tr><td class="altrow-a-0">PEUGEOT</td><td class="altrow-a-0">1987-1989</td></tr><tr><td class="altrow-a-1">PONTIAC</td><td class="altrow-a-1">1993-2010</td></tr><tr><td class="altrow-a-0">PORSCHE</td><td class="altrow-a-0">1994-2018</td></tr><tr><td class="altrow-a-1">RAM</td><td class="altrow-a-1">2011-2022</td></tr><tr><td class="altrow-a-0">SAAB</td><td class="altrow-a-0">1991-2005</td></tr><tr><td class="altrow-a-1">SATURN</td><td class="altrow-a-1">1993-2010</td></tr><tr><td class="altrow-a-0">SCION</td><td class="altrow-a-0">2006-2013</td></tr><tr><td class="altrow-a-1">SUBARU</td><td class="altrow-a-1">2000-2022</td></tr><tr><td class="altrow-a-0">SUZUKI</td><td class="altrow-a-0">1992-2012</td></tr><tr><td class="altrow-a-1">TOYOTA</td><td class="altrow-a-1">1994-2023</td></tr></table><div>Please refer to catalog for application details.</div></div></div>',
  'title': "Buyer's Guide :   Brake Fluid"},
 'groupindex': None,
 'collected_javascript': '/**UQ:970661A2**/\nwindow.top.parent.window["_nck"] = "8LVLUxTaILBT+tLxkg8+3Ag7\\/0bbOhvn7P3rkFbL80\\/oQB6RvzNfa5dcHvATqXAMxw5whzaDEdxk+27zeij67BjKru6WqTdNqG6tiEsD1EZhbTv0XForkbYp+nLaIKxDJ3DAD\\/oIoMxoM8tHV9xkwLS4u1P+JTCuX4Mbz0J3YOg=";\n'}

In [7]:
from bs4 import BeautifulSoup

In [8]:
html = resp['buyersguidepieces']['body']

soup = BeautifulSoup(html, 'lxml')

with open('./category.html', 'w', encoding='UTF-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <body>
  <div class="buyersguide-nested">
   <div style="padding: .5em;">
    <div>
     Results may be incomplete due to size of result set
    </div>
    <table class="nobmp" style="width: 100%;">
     <tr>
      <td class="altrow-a-0">
       ACURA
      </td>
      <td class="altrow-a-0">
       1996-2022
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       ALFA ROMEO
      </td>
      <td class="altrow-a-1">
       2018-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       BMW
      </td>
      <td class="altrow-a-0">
       1986-2014
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       BUICK
      </td>
      <td class="altrow-a-1">
       1993-2020
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       CADILLAC
      </td>
      <td class="altrow-a-0">
       1996-2022
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       CHEVROLET
      </td>
      <td class="altrow-a-1">
       1985-2024
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       CHRYSLER
      </td>
      <td class="altrow-a-0">
       1988-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       DAEWOO
      </td>
      <td class="altrow-a-1">
       1999-2000
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       DODGE
      </td>
      <td class="altrow-a-0">
       1989-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       FERRARI
      </td>
      <td class="altrow-a-1">
       1990-2016
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       FIAT
      </td>
      <td class="altrow-a-0">
       2012-2020
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       FORD
      </td>
      <td class="altrow-a-1">
       1993-2013
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       GENESIS
      </td>
      <td class="altrow-a-0">
       2018-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       GMC
      </td>
      <td class="altrow-a-1">
       1994-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       HONDA
      </td>
      <td class="altrow-a-0">
       1985-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       HUMMER
      </td>
      <td class="altrow-a-1">
       2004-2005
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       HYUNDAI
      </td>
      <td class="altrow-a-0">
       2000-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       INFINITI
      </td>
      <td class="altrow-a-1">
       1992-2022
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       ISUZU
      </td>
      <td class="altrow-a-0">
       1988-1997
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       JAGUAR
      </td>
      <td class="altrow-a-1">
       1992-2008
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       JEEP
      </td>
      <td class="altrow-a-0">
       1987-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       KIA
      </td>
      <td class="altrow-a-1">
       2002-2024
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LAMBORGHINI
      </td>
      <td class="altrow-a-0">
       1991-1992
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       LAND ROVER
      </td>
      <td class="altrow-a-1">
       1995-2007
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LEXUS
      </td>
      <td class="altrow-a-0">
       1990-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       LINCOLN
      </td>
      <td class="altrow-a-1">
       2000-2014
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LOTUS
      </td>
      <td class="altrow-a-0">
       1990-2017
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       MASERATI
      </td>
      <td class="altrow-a-1">
       2003-2017
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       MAZDA
      </td>
      <td class="altrow-a-0">
       1991-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       MERCURY
      </td>
      <td class="altrow-a-1">
       2004-2011
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       MINI
      </td>
      <td class="altrow-a-0">
       2007-2008
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       MITSUBISHI
      </td>
      <td class="altrow-a-1">
       1991-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       NISSAN
      </td>
      <td class="altrow-a-0">
       1991-2023
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       OLDSMOBILE
      </td>
      <td class="altrow-a-1">
       1985-2003
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       PEUGEOT
      </td>
      <td class="altrow-a-0">
       1987-1989
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       PONTIAC
      </td>
      <td class="altrow-a-1">
       1993-2010
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       PORSCHE
      </td>
      <td class="altrow-a-0">
       1994-2018
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       RAM
      </td>
      <td class="altrow-a-1">
       2011-2022
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       SAAB
      </td>
      <td class="altrow-a-0">
       1991-2005
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       SATURN
      </td>
      <td class="altrow-a-1">
       1993-2010
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       SCION
      </td>
      <td class="altrow-a-0">
       2006-2013
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       SUBARU
      </td>
      <td class="altrow-a-1">
       2000-2022
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       SUZUKI
      </td>
      <td class="altrow-a-0">
       1992-2012
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       TOYOTA
      </td>
      <td class="altrow-a-1">
       1994-2023
      </td>
     </tr>
    </table>
    <div>
     Please refer to catalog for application details.
    </div>
   </div>
  </div>
 </body>
</html>

In [9]:
from lxml import etree

In [10]:
html = etree.HTML(str(soup))

list_vehicle = html.xpath('//div[contains(@class, "buyersguide-nested")]/descendant::table[contains(@class, "nobmp")]/tr')

vehicle = '\n'.join([' '.join(_.xpath('./td/text()')) for _ in list_vehicle])

print(vehicle)

ACURA 1996-2022
ALFA ROMEO 2018-2023
BMW 1986-2014
BUICK 1993-2020
CADILLAC 1996-2022
CHEVROLET 1985-2024
CHRYSLER 1988-2023
DAEWOO 1999-2000
DODGE 1989-2023
FERRARI 1990-2016
FIAT 2012-2020
FORD 1993-2013
GENESIS 2018-2023
GMC 1994-2023
HONDA 1985-2023
HUMMER 2004-2005
HYUNDAI 2000-2023
INFINITI 1992-2022
ISUZU 1988-1997
JAGUAR 1992-2008
JEEP 1987-2023
KIA 2002-2024
LAMBORGHINI 1991-1992
LAND ROVER 1995-2007
LEXUS 1990-2023
LINCOLN 2000-2014
LOTUS 1990-2017
MASERATI 2003-2017
MAZDA 1991-2023
MERCURY 2004-2011
MINI 2007-2008
MITSUBISHI 1991-2023
NISSAN 1991-2023
OLDSMOBILE 1985-2003
PEUGEOT 1987-1989
PONTIAC 1993-2010
PORSCHE 1994-2018
RAM 2011-2022
SAAB 1991-2005
SATURN 1993-2010
SCION 2006-2013
SUBARU 2000-2022
SUZUKI 1992-2012
TOYOTA 1994-2023

In [11]:
df_temp = pd.DataFrame([{'status': 'ok',
                         'Type_Code': type_code,
                         'Part_Key': part_key,
                         'JOIN': type_code + ';' + part_key,
                         'Vehicle': vehicle}])

df = pd.concat([df, df_temp], ignore_index=True).fillna('')

df

,status,Type_Code,Part_Key,JOIN,Vehicle
0,ok,11389,13651017,11389;13651017,ACURA 1996-2022\nALFA ROMEO 2018-2023\nBMW 198...