In [1]:
import os

list_file = sorted(list(os.walk('./file/8.kit_part'))[0][2])
while '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
while '0.null.txt' in list_file:
    list_file.remove('0.null.txt')

list_file

['crawler_1.xlsx']

In [2]:
file = list_file[0]

file

'crawler_1.xlsx'

In [3]:
import pandas as pd

output_correct, output_error = pd.DataFrame(), pd.DataFrame()

In [4]:
input_ = pd.read_excel(f'./file/8.kit_part/{file}',
                       header=0,
                       dtype=str).fillna('')

print(f'总数量：{len(input_)}')
input_['Kit_JOIN_MPNTCPC'].tolist()

总数量：41

['MELLING;1025;5724;8921164',
 'MELLING;1026;5724;8921168',
 'MELLING;470;5724;10110008',
 'MELLING;471;5724;10110012',
 'MELLING;715F;5724;8306448',
 'MELLING;717F;5568;8527968',
 'MELLING;722F;5724;9659040',
 'MELLING;BG5053;5728;9659056',
 'MELLING;BG5054;5728;9659060',
 'MELLING;BG5062;5728;9722104',
 'MELLING;BG5063;5728;9722108',
 'MELLING;BG5515;5728;8307424',
 'MELLING;BG5622;5728;10110016',
 'MELLING;BG5623;5728;10110020',
 'MELLING;BG7019;11859;8921276',
 'MELLING;BT5066;5736;9659088',
 'MELLING;BT5068;5736;9659092',
 'MELLING;BT5069;5728;9659096',
 'MELLING;BT5070;5728;9659100',
 'MELLING;BT5077;5736;9659104',
 'MELLING;BT5078;5736;9659108',
 'MELLING;BT5079;5736;8921288',
 'MELLING;BT5514;5736;8308132',
 'MELLING;BT5618;5736;10110028',
 'MELLING;BT5619;5736;10110032',
 'MELLING;BT5620;5736;10110036',
 'MELLING;BT5621;5728;10110040',
 'MELLING;BT7015;5728;8308292',
 'MELLING;BT7016;11860;8308296',
 'MELLING;S1251;5723;9659204',
 'MELLING;S1261;5723;9659208',
 'MELLING;S1274;5722;9659212',
 'MELLING;S1276;5722;9659216',
 'MELLING;S1278;5722;9659220',
 'MELLING;S1290;10465;9659228',
 'MELLING;S899;5723;8314844',
 'MELLING;S905;5589;8921472',
 'MELLING;S906A;5722;8314860',
 'MELLING;S959;5723;10454636',
 'MELLING;S960;5722;10454640',
 'MELLING;S961;10465;10454644']

In [5]:
a = 0

a

0

In [6]:
crawler_status = 'error'

crawler_status

'error'

In [7]:
import requests
import json

import sys
sys.path.append('../00.Tools')
from crawler_configuration import get_header, get_proxy

payload = {'partData': {'listing_data_essential': {'parttype': input_.loc[a, 'Kit_Type Code'],
                                                   'partkey': input_.loc[a, 'Kit_Part Code']},
                        'listing_data_supplemental': {'partnumber': input_.loc[a, 'Kit_Part Number'],
                                                      'catalogname': input_.loc[a, 'Kit_Manufacturer']}}}

data = {'func': 'getbuyersguide',
        'payload': json.dumps(payload),
        'api_json_request': '1'}

b = 0
while True:
    b += 1
    print(b)
    try:
        check_url = input_.loc[a, 'Kit_Url']
        
        resp = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                             data=data,
                             headers=get_header(),
                             proxies=get_proxy(),
                             timeout=(10, 10))

        if resp.status_code == 200:
            dict_ = resp.json()
    
            if 'redirect_to_url' not in dict_ and dict_['buyersguidepieces']['title'].startswith('Buyer\'s Guide :') and 'collected_javascript' in dict_:
                break
    except KeyboardInterrupt:
        break
    except:
        continue

resp

1

In [8]:
from bs4 import BeautifulSoup
from lxml import etree

soup = BeautifulSoup(dict_['buyersguidepieces']['body'], 'lxml')
html = etree.HTML(str(soup))

with open('./kit_vehicle.html', 'w', encoding='UTF-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <body>
  <div class="buyersguide-nested">
   <div style="padding: .5em;">
    <table class="nobmp" style="width: 100%;">
     <tr>
      <td class="altrow-a-0">
       LEXUS
      </td>
      <td class="altrow-a-0">
       ES350
      </td>
      <td class="altrow-a-0">
       2007-2018
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       LEXUS
      </td>
      <td class="altrow-a-1">
       GS300
      </td>
      <td class="altrow-a-1">
       2006
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LEXUS
      </td>
      <td class="altrow-a-0">
       GS350
      </td>
      <td class="altrow-a-0">
       2007-2015
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       LEXUS
      </td>
      <td class="altrow-a-1">
       GS450H
      </td>
      <td class="altrow-a-1">
       2007-2011
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LEXUS
      </td>
      <td class="altrow-a-0">
       IS250
      </td>
      <td class="altrow-a-0">
       2006-2015
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       LEXUS
      </td>
      <td class="altrow-a-1">
       IS300
      </td>
      <td class="altrow-a-1">
       2016-2018
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LEXUS
      </td>
      <td class="altrow-a-0">
       IS350
      </td>
      <td class="altrow-a-0">
       2006-2017
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       LEXUS
      </td>
      <td class="altrow-a-1">
       RC300
      </td>
      <td class="altrow-a-1">
       2016-2018
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LEXUS
      </td>
      <td class="altrow-a-0">
       RC350
      </td>
      <td class="altrow-a-0">
       2015-2018
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       LEXUS
      </td>
      <td class="altrow-a-1">
       RX350
      </td>
      <td class="altrow-a-1">
       2007-2015
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       LEXUS
      </td>
      <td class="altrow-a-0">
       RX450H
      </td>
      <td class="altrow-a-0">
       2010-2015
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       TOYOTA
      </td>
      <td class="altrow-a-1">
       AVALON
      </td>
      <td class="altrow-a-1">
       2005-2018
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       TOYOTA
      </td>
      <td class="altrow-a-0">
       CAMRY
      </td>
      <td class="altrow-a-0">
       2007-2017
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       TOYOTA
      </td>
      <td class="altrow-a-1">
       HIGHLANDER
      </td>
      <td class="altrow-a-1">
       2008-2016
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       TOYOTA
      </td>
      <td class="altrow-a-0">
       RAV4
      </td>
      <td class="altrow-a-0">
       2006-2012
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       TOYOTA
      </td>
      <td class="altrow-a-1">
       SIENNA
      </td>
      <td class="altrow-a-1">
       2007-2016
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       TOYOTA
      </td>
      <td class="altrow-a-0">
       VENZA
      </td>
      <td class="altrow-a-0">
       2009-2015
      </td>
     </tr>
    </table>
    <div>
     Please refer to catalog for application details.
    </div>
   </div>
  </div>
 </body>
</html>

In [9]:
len(html.xpath('//p/text()')) != 0 and html.xpath('//p/text()')[0] == 'No applications found.'

False

In [10]:
list_tr = html.xpath('//tr')

list_tr

[<Element tr at 0x11e624900>,
 <Element tr at 0x11e625b40>,
 <Element tr at 0x11e6259c0>,
 <Element tr at 0x11e625ac0>,
 <Element tr at 0x11e626200>,
 <Element tr at 0x11e77c2c0>,
 <Element tr at 0x11e77fb40>,
 <Element tr at 0x11e77e3c0>,
 <Element tr at 0x11e77f1c0>,
 <Element tr at 0x11e77c400>,
 <Element tr at 0x11e77cc80>,
 <Element tr at 0x11e77f180>,
 <Element tr at 0x11e77c480>,
 <Element tr at 0x11e77d000>,
 <Element tr at 0x11e77d9c0>,
 <Element tr at 0x11e77d400>,
 <Element tr at 0x11e77e4c0>]

In [11]:
len(list_tr) == 0

False

In [12]:
df_temp = pd.DataFrame()
for i, tr in enumerate(list_tr):
    list_text = [text.strip() for text in tr.xpath('./td/text()')]

    if len(list_text) == 3:
        if '-' in list_text[2]:
            [year_begin, year_end] = list_text[2].split('-')
            for year in range(int(year_begin), int(year_end) + 1):
                df_temp_temp = pd.DataFrame([{'Kit_Part Number': input_.loc[a, 'Kit_Part Number'],
                                              'Kit_JOIN_MPNTCPC': input_.loc[a, 'Kit_JOIN_MPNTCPC'],
                                              'Vehicle No': i + 1,
                                              'Make': list_text[0],
                                              'Model': list_text[1],
                                              'Year': year}])
                df_temp = pd.concat([df_temp, df_temp_temp], ignore_index=True).fillna('')
        else:
            df_temp_temp = pd.DataFrame([{'Kit_Part Number': input_.loc[a, 'Kit_Part Number'],
                                          'Kit_JOIN_MPNTCPC': input_.loc[a, 'Kit_JOIN_MPNTCPC'],
                                          'Vehicle No': i + 1,
                                          'Make': list_text[0],
                                          'Model': list_text[1],
                                          'Year': int(list_text[2])}])
            df_temp = pd.concat([df_temp, df_temp_temp], ignore_index=True).fillna('')
    elif len(list_text) == 2:
        if '-' in list_text[1]:
            [year_begin, year_end] = list_text[1].split('-')
            for year in range(int(year_begin), int(year_end) + 1):
                df_temp_temp = pd.DataFrame([{'Kit_Part Number': input_.loc[a, 'Kit_Part Number'],
                                              'Kit_JOIN_MPNTCPC': input_.loc[a, 'Kit_JOIN_MPNTCPC'],
                                              'Vehicle No': i + 1,
                                              'Make': list_text[0],
                                              'Model': '',
                                              'Year': year}])
                df_temp = pd.concat([df_temp, df_temp_temp], ignore_index=True).fillna('')
        else:
            df_temp_temp = pd.DataFrame([{'Kit_Part Number': input_.loc[a, 'Kit_Part Number'],
                                          'JOIN_MPNTCPC': input_.loc[a, 'JOIN_MPNTCPC'],
                                          'Vehicle No': i + 1,
                                          'Make': list_text[0],
                                          'Model': '',
                                          'Year': int(list_text[1])}])
            df_temp = pd.concat([df_temp, df_temp_temp], ignore_index=True).fillna('')
    else:
        print('fuck')

output_correct = pd.concat([output_correct, df_temp], ignore_index=True).fillna('')

output_correct

,Kit_Part Number,Kit_JOIN_MPNTCPC,Vehicle No,Make,Model,Year
0,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2007
1,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2008
2,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2009
3,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2010
4,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2011
...,...,...,...,...,...,...
127,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2011
128,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2012
129,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2013
130,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2014
131,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2015

In [13]:
crawler_status = 'ok'

crawler_status

'ok'

In [14]:
if crawler_status == 'error':
    df_temp = pd.DataFrame([input_.iloc[a]]).reset_index(drop=True)
    df_temp.loc[0, 'Check_Url'] = check_url
    
    output_error = pd.concat([output_error, df_temp], ignore_index=True).fillna('')

output_error

Empty DataFrame
Columns: []
Index: []

In [15]:
if not output_correct.empty:
    output_correct = output_correct.sort_values(by=['Kit_JOIN_MPNTCPC', 'Vehicle No', 'Year'],
                                                ascending=[True, True, False],
                                                ignore_index=True)
    output_correct.to_excel('./test_kit_vehicle.xlsx', index=False)

output_correct

,Kit_Part Number,Kit_JOIN_MPNTCPC,Vehicle No,Make,Model,Year
0,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2018
1,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2017
2,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2016
3,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2015
4,1025,MELLING;1025;5724;8921164,1,LEXUS,ES350,2014
...,...,...,...,...,...,...
127,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2013
128,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2012
129,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2011
130,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2010
131,1025,MELLING;1025;5724;8921164,17,TOYOTA,VENZA,2009

In [16]:
if not output_error.empty:
    output_error = output_error.sort_values(by=['Kit_JOIN_MPNTCPC'],
                                            ascending=[True],
                                            ignore_index=True)
    output_error.to_excel('./test_kit_vehicle_error.xlsx', index=False)

output_error

Empty DataFrame
Columns: []
Index: []