In [1]:
import pandas as pd

input_ = pd.read_excel(f'./5.vehicle_1.xlsx',
                       header=0,
                       dtype=str).fillna('')

input_

,No,Item Number,Market,Page,JOIN_INP,Row,Make,Model,Year,Submodel,Variant,Engine,Notes
0,1,192511998212,AU,1,192511998212;1,1,Lexus,LX,2007,UZJ100 SUV 470,AWD Petrol 4.7L 8cyl 170kW 2UZ-FE,4664cc 170kW (Petrol),"Please, contact a dealer for a correct Part Nu..."
1,1,192511998212,AU,1,192511998212;1,2,Lexus,LX,2006,UZJ100 SUV 470,AWD Petrol 4.7L 8cyl 170kW 2UZ-FE,4664cc 170kW (Petrol),"Please, contact a dealer for a correct Part Nu..."
2,1,192511998212,AU,1,192511998212;1,3,Lexus,LX,2005,UZJ100 SUV 470,AWD Petrol 4.7L 8cyl 170kW 2UZ-FE,4664cc 170kW (Petrol),"Please, contact a dealer for a correct Part Nu..."
3,1,192511998212,AU,1,192511998212;1,4,Lexus,LX,2004,UZJ100 SUV 470,AWD Petrol 4.7L 8cyl 170kW 2UZ-FE,4664cc 170kW (Petrol),"Please, contact a dealer for a correct Part Nu..."
4,1,192511998212,AU,1,192511998212;1,5,Lexus,LX,2003,UZJ100 SUV 470,AWD Petrol 4.7L 8cyl 170kW 2UZ-FE,4664cc 170kW (Petrol),"Please, contact a dealer for a correct Part Nu..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4132,30,195669368319,AU,12,195669368319;12,17,Toyota,Hilux,1983,LN56 Ute 2.2 D,RWD Diesel 2.2L 4cyl 49kW L,2188cc 49kW (Diesel),"Please, contact a dealer for a correct Part Nu..."
4133,30,195669368319,AU,12,195669368319;12,18,Toyota,Hilux,1983,LN56 Ute 2.2 D 4WD,AWD Diesel 2.2L 4cyl 49kW L,2188cc 49kW (Diesel),"Please, contact a dealer for a correct Part Nu..."
4134,30,195669368319,AU,12,195669368319;12,19,Toyota,Hilux,1983,LN65 Ute 2.4 D 4WD,AWD Diesel 2.4L 4cyl 55kW 2L,2446cc 55kW (Diesel),"Please, contact a dealer for a correct Part Nu..."
4135,30,195669368319,AU,12,195669368319;12,20,Toyota,Hilux,1983,YN56 Ute 1.8,"RWD Petrol 1.8L 4cyl 58kW 2Y,2Y-C",1812cc 58kW (Petrol),"Please, contact a dealer for a correct Part Nu..."
4136,30,195669368319,AU,13,195669368319;13,1,Toyota,Hilux,1983,YN65 Ute 2.0 4WD,"AWD Petrol 2.0L 4cyl 65kW 3Y,3Y-C",1998cc 65kW (Petrol),"Please, contact a dealer for a correct Part Nu..."

In [2]:
input_2 = input_[['Item Number']].drop_duplicates(keep='first', ignore_index=True)
input_2 = input_2.sort_values(by=['Item Number'],
                              ascending=[True],
                              ignore_index=True)

input_2

     Item Number
0   192335808616
1   192399272603
2   192461026915
3   192461027622
4   192461035908
5   192461036905
6   192461038502
7   192461038654
8   192461039242
9   192461039631
10  192461040906
11  192469913773
12  192470815384
13  192470816410
14  192511998212
15  192557565418
16  193432073359
17  193432073395
18  193432073431
19  193432073468
20  195656999183
21  195660971887
22  195669367960
23  195669368019
24  195669368087
25  195669368150
26  195669368239
27  195669368319
28  196084651183
29  196084651217

In [3]:
from tqdm import tqdm

for i in tqdm(range(len(input_2)), desc='Progress', ncols=77):
    df_temp = input_[input_['Item Number'] == input_2.loc[i, 'Item Number']].copy().reset_index(drop=True)

    # = = = = = = = = = = = = = = =

    dict_vehicle = {}
    for j in range(len(df_temp)):
        if df_temp.loc[j, 'Market'] in ['US', 'UK', 'AU']:
            make, model, engine, year, year_2 = df_temp.loc[j, 'Make'], df_temp.loc[j, 'Model'], df_temp.loc[j, 'Engine'], int(df_temp.loc[j, 'Year']), int(df_temp.loc[j, 'Year'])
        elif df_temp.loc[j, 'Market'] == 'DE':
            make, model, engine, year, year_2 = df_temp.loc[j, 'Marke'], df_temp.loc[j, 'Modell'], df_temp.loc[j, 'Motor'], int(df_temp.loc[j, 'Baujahr'].split('-')[0].split('/')[0]), int(df_temp.loc[j, 'Baujahr'].split('-')[1].split('/')[0])

        if make not in dict_vehicle.keys():
            dict_vehicle[make] = {model: {engine: [year]}}
        elif model not in dict_vehicle[make].keys():
            dict_vehicle[make][model] = {engine: [year]}
        elif engine not in dict_vehicle[make][model].keys():
            dict_vehicle[make][model][engine] = [year]
        else:
            if year not in dict_vehicle[make][model][engine]:
                dict_vehicle[make][model][engine].append(year)
            if year_2 not in dict_vehicle[make][model][engine]:
                dict_vehicle[make][model][engine].append(year_2)

    # = = = = = = = = = = = = = = =

    list_vehicle = []
    for make in dict_vehicle.keys():
        for model in dict_vehicle[make].keys():
            list_year = []
            for engine in dict_vehicle[make][model].keys():
                list_year = list(set(list_year + dict_vehicle[make][model][engine]))
            year_begin = min(list_year)
            year_end = max(list_year)
            list_vehicle.append(f'{make} {model} {year_begin}' if year_begin == year_end else f'{make} {model} {year_begin}-{year_end}')

    input_2.loc[i, 'Vehicle W/o Engine'] = '\n'.join(list_vehicle)

    # = = = = = = = = = = = = = = =

    list_vehicle = []
    for make in dict_vehicle.keys():
        for model in dict_vehicle[make].keys():
            for engine in dict_vehicle[make][model].keys():
                year_begin = min(dict_vehicle[make][model][engine])
                year_end = max(dict_vehicle[make][model][engine])
                list_vehicle.append(f'{make} {model} {year_begin} {engine}'.strip() if year_begin == year_end else f'{make} {model} {year_begin}-{year_end} {engine}'.strip())

    input_2.loc[i, 'Vehicle W/ Engine'] = '\n'.join(list_vehicle)

    # = = = = = = = = = = = = = = =

input_2.to_excel('./6.vehicle.xlsx', index=False)

input_2

Progress: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 30/30 [00:00<00:00, 179.11it/s]

,Item Number,Vehicle W/o Engine,Vehicle W/ Engine
0,192335808616,Lexus LX 2007-2015\nToyota LandCruiser 2007-2015,Lexus LX 2007-2015 5663cc 270kW (Petrol)\nToyo...
1,192399272603,Toyota LandCruiser 1998-2007,Toyota LandCruiser 1998-2007 4164cc 150kW (Die...
2,192461026915,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
3,192461027622,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
4,192461035908,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
5,192461036905,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
6,192461038502,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
7,192461038654,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
8,192461039242,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
9,192461039631,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
10,192461040906,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
11,192469913773,Toyota LandCruiser 1998-2007,Toyota LandCruiser 1998-2007 4164cc 150kW (Die...
12,192470815384,Lexus LX 2007-2015\nToyota LandCruiser 2007-2015,Lexus LX 2007-2015 5663cc 270kW (Petrol)\nToyo...
13,192470816410,Lexus LX 2007-2015\nToyota LandCruiser 2007-2015,Lexus LX 2007-2015 5663cc 270kW (Petrol)\nToyo...
14,192511998212,Lexus LX 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)
15,192557565418,Lexus LX 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)
16,193432073359,Lexus LX 1998-2007\nToyota LandCruiser 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)\nToyo...
17,193432073395,Lexus LX 1998-2007\nToyota LandCruiser 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)\nToyo...
18,193432073431,Lexus LX 1998-2007\nToyota LandCruiser 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)\nToyo...
19,193432073468,Lexus LX 1998-2007\nToyota LandCruiser 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)\nToyo...
20,195656999183,Toyota LandCruiser 1998-2007,Toyota LandCruiser 1998-2007 4164cc 150kW (Die...
21,195660971887,Lexus LX 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)
22,195669367960,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
23,195669368019,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
24,195669368087,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
25,195669368150,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
26,195669368239,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
27,195669368319,Toyota LandCruiser 1984-2007\nToyota 4 Runner ...,Toyota LandCruiser 2001-2007 4164cc 122kW (Die...
28,196084651183,Lexus LX 1998-2007\nToyota LandCruiser 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)\nToyo...
29,196084651217,Lexus LX 1998-2007\nToyota LandCruiser 1998-2007,Lexus LX 1998-2007 4664cc 170kW (Petrol)\nToyo...