In [1]:
import os
import datetime

In [2]:
list_file = list(os.walk('./'))[0][2]
for file in list_file:
    if '计算表' in file:
        calculate = file

print(f'calculate: \t{calculate}')

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel(calculate,
                   sheet_name='附_1统计源（含新品、清仓、新品成长）',
                   header=3,
                   usecols=[2, 3, 5, 11, 12])

df

             MRP SKU  目标\n周销  Level   在库   在途
0       USTBC40007-C   41.60   TOP1  264  418
1      USHB13158-2-C    9.93  TOP20    0    2
2       USBM00237D-C   24.54   TOP1   57  126
3       USBM00191D-C   11.78  TOP10  113    0
4       USSGTO012T-C   18.04   TOP1  128  120
...              ...     ...    ...  ...  ...
55881     USWRM48301    0.50     普通    0    3
55882     USWRM51020    1.00     普通    0    7
55883     USWRM51021    1.00     普通    0   10
55884     USWRM51022    0.50     普通    0    6
55885     USWRM51023    0.50     普通    0    6

[55886 rows x 5 columns]

In [5]:
df = df[(df['在库']==0) & (df['在途']==0) & (df['Level']!='普通')][['MRP SKU',
                                                                   'Level',
                                                                   '目标\n周销',
                                                                   '在途']]

df

              MRP SKU  Level  目标\n周销  在途
85     USBCN87020LR-C  TOP20    5.31   0
527      USCAKTE004-C  TOP20    1.29   0
544      USACC29043-C  TOP10    4.25   0
545      USACC29252-C  TOP10    4.25   0
1165   USFP7263M0Z1-C   TOP1    2.91   0
...               ...    ...     ...  ..
51375    USCAK20990-C  TOP20    1.72   0
51396    USCAK21017-C  TOP10    1.27   0
51968    USCAK53610-C  TOP10    2.55   0
52124  USBRPS231971FR  TOP10    2.38   0
53208    USCAK54524LR  TOP20    0.82   0

[110 rows x 4 columns]

In [6]:
df = df.sort_values(by=['Level', 'MRP SKU'], ascending=[True, True])

df

              MRP SKU  Level  目标\n周销  在途
39411    USADCA00400U   TOP1    7.65   0
8136     USBCB97430-C   TOP1    5.47   0
1165   USFP7263M0Z1-C   TOP1    2.91   0
9978     USPBB27358-C   TOP1    1.49   0
22111    USPSR221014G   TOP1    2.62   0
...               ...    ...     ...  ..
28790      USSKA51216  TOP20    1.70   0
45017    USSTR19163-C  TOP20    0.68   0
9611    USSTR66760B-C  TOP20    3.40   0
9098    USWHN11094-20  TOP20    2.12   0
1317      USWM42269HY  TOP20    5.41   0

[110 rows x 4 columns]

In [7]:
import datetime

In [8]:
writer = pd.ExcelWriter('Lennon_筛选好的断货SKU_' + datetime.datetime.now().strftime("%Y%m%d_%H%M%S") + '.xlsx')
df.to_excel(writer, index=False)
writer.close()