In [1]:
import pandas as pd

output_correct, output_error = pd.DataFrame(), pd.DataFrame()

In [2]:
input_ = pd.read_excel(f'./file/4.page.xlsx',
                       header=0,
                       dtype=str).fillna('')

input_['Year'] = input_['Year'].astype(int)
input_['SKU Count'] = input_['SKU Count'].astype(int)
input_['Page'] = input_['Page'].astype(int)

print(f'总数量：{len(input_)}')
input_['SKU Count'].tolist()

总数量：19262

[10,
 10,
 10,
 9,
 9,
 9,
 2,
 4,
 17,
 17,
 19,
 19,
 18,
 18,
 18,
 18,
 21,
 21,
 31,
 31,
 49,
 49,
 29,
 29,
 6,
 11,
 11,
 10,
 11,
 11,
 11,
 11,
 11,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 13,
 13,
 13,
 11,
 10,
 4,
 4,
 3,
 3,
 4,
 4,
 18,
 18,
 20,
 20,
 25,
 25,
 27,
 27,
 28,
 28,
 29,
 29,
 44,
 44,
 29,
 29,
 25,
 25,
 26,
 26,
 26,
 26,
 24,
 24,
 24,
 24,
 24,
 24,
 17,
 17,
 16,
 16,
 8,
 9,
 9,
 9,
 2,
 5,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 2,
 2,
 24,
 24,
 26,
 26,
 25,
 25,
 28,
 28,
 28,
 28,
 26,
 26,
 29,
 29,
 48,
 48,
 29,
 29,
 27,
 27,
 27,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 18,
 18,
 18,
 18,
 17,
 17,
 23,
 23,
 24,
 24,
 25,
 25,
 48,
 48,
 10,
 13,
 13,
 13,
 13,
 8,
 8,
 8,
 45,
 45,
 27,
 27,
 28,
 28,
 27,
 27,
 28,
 28,
 28,
 28,
 26,
 26,
 26,
 26,
 23,
 23,
 23,
 23,
 13,
 11,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 9,
 2,
 2,
 6,
 30,
 30,
 30,
 30,
 31,
 31,
 29,
 29,
 29,
 29,
 29,
 29,
 46,
 46,
 25,
 25,
 25,
 25,
 24,
 24,
 23,
 23,
 23,
 23,
 18,
 18,
 18,
 18,
 18,
 18,
 19,
 19,
 9,
 6,
 6,
 6,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 30,
 30,
 30,
 29,
 30,
 30,
 29,
 29,
 29,
 29,
 30,
 29,
 28,
 29,
 29,
 29,
 10,
 10,
 10,
 4,
 4,
 3,
 10,
 10,
 10,
 4,
 4,
 4,
 6,
 6,
 6,
 6,
 6,
 6,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 11,
 11,
 11,
 2,
 2,
 2,
 2,
 11,
 11,
 11,
 1,
 1,
 1,
 1,
 29,
 29,
 22,
 31,
 30,
 30,
 30,
 30,
 31,
 30,
 29,
 29,
 29,
 29,
 29,
 29,
 7,
 8,
 7,
 7,
 8,
 7,
 6,
 6,
 1,
 1,
 8,
 18,
 18,
 18,
 18,
 18,
 14,
 15,
 15,
 15,
 16,
 14,
 14,
 14,
 19,
 19,
 19,
 3,
 3,
 10,
 17,
 26,
 26,
 27,
 27,
 27,
 27,
 21,
 21,
 21,
 21,
 26,
 26,
 26,
 35,
 22,
 22,
 24,
 24,
 21,
 18,
 18,
 13,
 13,
 14,
 16,
 15,
 10,
 28,
 28,
 28,
 28,
 24,
 30,
 30,
 30,
 31,
 31,
 29,
 29,
 28,
 28,
 28,
 28,
 24,
 30,
 30,
 31,
 31,
 31,
 29,
 29,
 28,
 28,
 28,
 28,
 24,
 28,
 28,
 28,
 28,
 24,
 5,
 5,
 5,
 17,
 17,
 17,
 17,
 21,
 21,
 21,
 21,
 28,
 28,
 28,
 38,
 24,
 24,
 25,
 26,
 23,
 20,
 20,
 16,
 16,
 17,
 16,
 14,
 10,
 30,
 30,
 30,
 31,
 31,
 29,
 29,
 28,
 28,
 28,
 28,
 24,
 4,
 4,
 5,
 17,
 17,
 17,
 18,
 3,
 3,
 10,
 8,
 10,
 10,
 23,
 23,
 24,
 24,
 24,
 30,
 30,
 30,
 30,
 30,
 28,
 28,
 30,
 30,
 30,
 30,
 30,
 28,
 28,
 30,
 30,
 30,
 30,
 30,
 28,
 28,
 28,
 28,
 5,
 5,
 5,
 19,
 18,
 19,
 24,
 24,
 24,
 24,
 24,
 25,
 26,
 27,
 24,
 23,
 5,
 5,
 5,
 16,
 16,
 18,
 3,
 3,
 10,
 9,
 32,
 32,
 32,
 32,
 22,
 21,
 21,
 21,
 21,
 18,
 18,
 18,
 18,
 18,
 19,
 14,
 14,
 14,
 15,
 15,
 16,
 18,
 10,
 10,
 9,
 29,
 29,
 29,
 30,
 30,
 28,
 28,
 28,
 27,
 27,
 27,
 23,
 6,
 6,
 6,
 14,
 14,
 23,
 23,
 23,
 21,
 21,
 21,
 21,
 20,
 20,
 20,
 21,
 21,
 23,
 21,
 16,
 16,
 16,
 16,
 16,
 16,
 20,
 10,
 10,
 9,
 29,
 29,
 29,
 30,
 30,
 28,
 28,
 28,
 27,
 27,
 27,
 23,
 4,
 4,
 4,
 12,
 29,
 29,
 31,
 31,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 29,
 29,
 29,
 14,
 14,
 18,
 18,
 18,
 17,
 19,
 20,
 20,
 6,
 6,
 6,
 6,
 6,
 10,
 10,
 8,
 8,
 7,
 30,
 30,
 31,
 31,
 31,
 29,
 29,
 29,
 29,
 29,
 29,
 25,
 5,
 5,
 6,
 14,
 14,
 15,
 15,
 15,
 15,
 17,
 17,
 18,
 19,
 15,
 17,
 17,
 17,
 18,
 18,
 16,
 7,
 7,
 7,
 7,
 8,
 8,
 7,
 29,
 31,
 31,
 18,
 18,
 15,
 14,
 14,
 12,
 11,
 12,
 11,
 11,
 2,
 2,
 2,
 1,
 1,
 29,
 29,
 10,
 10,
 12,
 12,
 19,
 19,
 24,
 24,
 24,
 24,
 36,
 36,
 34,
 34,
 25,
 25,
 9,
 9,
 25,
 25,
 25,
 25,
 3,
 4,
 4,
 4,
 4,
 7,
 7,
 7,
 7,
 15,
 15,
 21,
 21,
 25,
 25,
 24,
 24,
 33,
 33,
 25,
 25,
 25,
 25,
 29,
 31,
 30,
 29,
 4,
 4,
 4,
 13,
 32,
 30,
 32,
 32,
 31,
 29,
 29,
 29,
 9,
 9,
 10,
 10,
 18,
 18,
 28,
 28,
 29,
 29,
 28,
 28,
 26,
 26,
 21,
 21,
 21,
 22,
 22,
 23,
 22,
 22,
 24,
 32,
 31,
 31,
 31,
 29,
 29,
 29,
 29,
 29,
 8,
 8,
 8,
 8,
 16,
 16,
 14,
 23,
 23,
 2,
 3,
 1,
 11,
 11,
 8,
 8,
 9,
 9,
 8,
 8,
 14,
 14,
 11,
 11,
 10,
 9,
 7,
 31,
 29,
 31,
 29,
 31,
 31,
 31,
 29,
 29,
 29,
 29,
 5,
 5,
 5,
 7,
 7,
 7,
 4,
 11,
 11,
 11,
 11,
 2,
 2,
 22,
 18,
 28,
 28,
 9,
 9,
 9,
 9,
 16,
 16,
 14,
 14,
 6,
 31,
 31,
 31,
 31,
 31,
 31,
 5,
 5,
 5,
 11,
 18,
 3,
 4,
 10,
 6,
 1,
 4,
 4,
 4,
 3,
 3,
 10,
 28,
 28,
 27,
 27,
 27,
 27,
 29,
 29,
 29,
 29,
 6,
 6,
 6,
 29,
 29,
 29,
 29,
 30,
 31,
 31,
 31,
 29,
 29,
 31,
 28,
 29,
 30,
 30,
 30,
 30,
 28,
 28,
 28,
 28,
 28,
 28,
 24,
 29,
 29,
 31,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 27,
 27,
 29,
 29,
 29,
 29,
 29,
 27,
 27,
 27,
 27,
 6,
 6,
 6,
 16,
 16,
 18,
 29,
 29,
 31,
 22,
 30,
 31,
 31,
 31,
 31,
 31,
 29,
 29,
 29,
 29,
 3,
 3,
 10,
 20,
 20,
 27,
 27,
 26,
 26,
 19,
 19,
 21,
 22,
 ...]

In [3]:
a = 0

a

0

In [4]:
crawler_status = 'error'

crawler_status

'error'

In [5]:
import requests

import sys
sys.path.append('../00.Tools')
from crawler_configuration import get_header, get_proxy

b = 0
while True:
    b += 1
    print(b)
    try:
        resp = requests.get(f'''https://www.auveco.com/store_ss2/extensions/UnlockCommerce/YearMakeModel/1.0.0/Modules/YearMakeModel/SuiteScript2/YearMakeModel.Service.ss?action=listbyymm&limit=100&make={input_.loc[a, 'Make']}&model={input_.loc[a, 'Model']}&offset={input_.loc[a, 'Page']*100-100}&page={input_.loc[a, 'Page']}&sort=relevance%3Adesc&year={input_.loc[a, 'Year']}''',
                            headers=get_header(),
                            proxies=get_proxy(),
                            timeout=(10, 10))

        if resp.status_code == 200:
            json_ = resp.json()

            list_item = [str(dict_['id']) for dict_ in json_['itemsId']]
            if json_['success'] == 'OK' and list_item:
                break
    except KeyboardInterrupt:
        break
    except:
        continue

list_item

1

['24830',
 '41273',
 '41276',
 '41277',
 '25521',
 '25761',
 '25762',
 '43379',
 '1792',
 '16615']

In [6]:
df_temp = pd.DataFrame([{'Make': input_.loc[a, 'Make'],
                         'Model': input_.loc[a, 'Model'],
                         'Year': input_.loc[a, 'Year'],
                         'SKU Count': input_.loc[a, 'SKU Count'],
                         'Page': input_.loc[a, 'Page'],
                         'Item': '%2C'.join(list_item)}])

output_correct = pd.concat([output_correct, df_temp], ignore_index=True).fillna('')

output_correct

,Make,Model,Year,SKU Count,Page,Item
0,ACURA,CL,2003,10,1,24830%2C41273%2C41276%2C41277%2C25521%2C25761%...

In [7]:
crawler_status = 'ok'

crawler_status

'ok'

In [8]:
if crawler_status == 'error':
    output_error = pd.concat([output_error, pd.DataFrame([input_.iloc[a]]).reset_index(drop=True)], ignore_index=True).fillna('')

output_error

Empty DataFrame
Columns: []
Index: []

In [9]:
if not output_correct.empty:
    output_correct = output_correct.sort_values(by=['Make', 'Model', 'Year', 'Page'],
                                                ascending=[True, True, False, True],
                                                ignore_index=True)
    output_correct.to_excel('./test_item.xlsx', index=False)

output_correct

,Make,Model,Year,SKU Count,Page,Item
0,ACURA,CL,2003,10,1,24830%2C41273%2C41276%2C41277%2C25521%2C25761%...

In [10]:
if not output_error.empty:
    output_error = output_error.sort_values(by=['Make', 'Model', 'Year', 'Page'],
                                            ascending=[True, True, False, True],
                                            ignore_index=True)
    output_error.to_excel('./test_item_error.xlsx', index=False)

output_error

Empty DataFrame
Columns: []
Index: []