- Update: 2023.04.14

In [1]:
import os
import datetime

In [2]:
list_file = list(os.walk('./'))[0][2]
for file in list_file:
    if '计算表' in file:
        calculate = file

print(f'calculate: \t{calculate}')

calculate: 	计算表-【每日断货汇报】US-Ebay 20230425.xlsx

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel(calculate,
                   sheet_name='附_1统计源（含新品、清仓、新品成长）',
                   header=3,
                   usecols=[2, 3, 5, 11, 12])

df

                 MRP SKU  目标\n周销  Level   在库   在途
0           USTBC40007-C   48.00   TOP1  144  319
1              USGS06060   30.99  TOP10  188  221
2           USWR645FRU-C   31.05   TOP1  215  154
3      USTCV17215HIE-2-C   24.73   TOP1   53  336
4              USWS02863   23.65   TOP1  136   65
...                  ...     ...    ...  ...  ...
52062     USBCB92873LR-C    0.00     普通    7   21
52063    USBCB93101ALR-C    0.70     普通    2   20
52064       USPSP69401-C    1.34     普通    2   27
52065      USTHB7003ZH-C    0.60     普通    3    0
52066     USBCB84929LR-C    0.70     普通    0    0

[52067 rows x 5 columns]

In [5]:
df = df[(df['在库']==0) & (df['在途']==0) & (df['Level']!='普通')][['MRP SKU',
                                                                   'Level',
                                                                   '目标\n周销',
                                                                   '在途']]

df

               MRP SKU  Level  目标\n周销  在途
99      USBCB97102LR-C  TOP10    2.34   0
132    USFFTOPO002S-YC  TOP20    4.50   0
291          USGS71780  TOP20    2.92   0
495    USCVA0HO108LR-C  TOP10    2.40   0
878      USSA65497-1-C  TOP20    1.87   0
...                ...    ...     ...  ..
45721     USBCB91608-C  TOP20    2.40   0
46645     USMI20283W-C  TOP10    7.22   0
49822   USICK61700-6-C  TOP10    1.60   0
51027  USFFCHOE005S-YC  TOP20    2.55   0
51456   USBRPS588805FR  TOP20    2.55   0

[93 rows x 4 columns]

In [6]:
import datetime

writer = pd.ExcelWriter('Lennon_筛选好的断货SKU_' + datetime.datetime.now().strftime("%Y%m%d_%H%M%S") + '.xlsx')
df.to_excel(writer, index=False)
writer.close()