In [1]:
import pandas as pd

output_correct = pd.DataFrame()
output_error = pd.DataFrame()

In [2]:
input_ = pd.read_excel('./part.xlsx',
                       header=0,
                       dtype=str).fillna('')

print('总数量：' + str(len(input_)))
input_['Part_Key'].tolist()

总数量：500

['8304960',
 '11158045',
 '8304968',
 '8304972',
 '8304976',
 '9658980',
 '9658984',
 '8304980',
 '10110000',
 '8304984',
 '15382989',
 '15382993',
 '9722076',
 '8304992',
 '13570025',
 '8305000',
 '10454500',
 '10454504',
 '8921200',
 '8921204',
 '8921208',
 '8921212',
 '9658988',
 '8305008',
 '8305012',
 '15583577',
 '8305016',
 '11158049',
 '13570029',
 '15583581',
 '15583585',
 '10890260',
 '10981368',
 '13570033',
 '8305020',
 '8305024',
 '11492461',
 '15583589',
 '15583593',
 '15382997',
 '15583597',
 '15583601',
 '8305028',
 '11158053',
 '10981372',
 '11158057',
 '8305032',
 '11158061',
 '10981376',
 '11158065',
 '8305036',
 '11158069',
 '10981380',
 '11158073',
 '8305040',
 '11158077',
 '15383001',
 '15383005',
 '10454508',
 '11158081',
 '15383009',
 '11158085',
 '11158089',
 '11158093',
 '12803989',
 '12803993',
 '12803997',
 '12804001',
 '12804005',
 '15383013',
 '15383017',
 '15383021',
 '15583609',
 '15383025',
 '12020433',
 '12804009',
 '12804013',
 '12020437',
 '8305044',
 '9722080',
 '9722084',
 '9854468',
 '9854472',
 '9854476',
 '9854480',
 '10890264',
 '10890268',
 '11158097',
 '11158101',
 '10890272',
 '11158105',
 '11158109',
 '11492465',
 '11492469',
 '12020453',
 '12020457',
 '12804017',
 '14047645',
 '13570041',
 '13570045',
 '13570049',
 '13570053',
 '14047649',
 '14047653',
 '14047657',
 '15383029',
 '15383033',
 '15383037',
 '15383041',
 '15383045',
 '15383049',
 '15383053',
 '15583613',
 '15583617',
 '14047661',
 '15583625',
 '14047665',
 '12020461',
 '15383057',
 '15383061',
 '15383065',
 '4492857',
 '5611497',
 '8305052',
 '5031129',
 '7315456',
 '7304668',
 '8305056',
 '5031132',
 '8305060',
 '8305064',
 '8305068',
 '5629017',
 '7075180',
 '8305076',
 '8305080',
 '8305084',
 '8305092',
 '8305096',
 '8305100',
 '8305104',
 '8527936',
 '8305108',
 '8527940',
 '8305112',
 '8305116',
 '8305156',
 '8305184',
 '7304672',
 '8305192',
 '8305196',
 '3950082',
 '8069848',
 '5031135',
 '7305776',
 '5031138',
 '5031141',
 '5031144',
 '7096416',
 '8305200',
 '12026925',
 '5031147',
 '5031150',
 '8305208',
 '5031153',
 '8305216',
 '10890276',
 '12902177',
 '8305232',
 '8305236',
 '8305240',
 '9854484',
 '8305244',
 '7075188',
 '8305248',
 '8305252',
 '8305256',
 '8305260',
 '8305264',
 '8305268',
 '8305276',
 '8305280',
 '11158121',
 '8305284',
 '8305288',
 '8305292',
 '14310121',
 '8305296',
 '8305300',
 '8305304',
 '14310125',
 '8305308',
 '8305312',
 '8305316',
 '11158125',
 '11158129',
 '8305320',
 '11158133',
 '11492477',
 '14310129',
 '11492481',
 '14310133',
 '12020469',
 '8305324',
 '8305328',
 '8305336',
 '8305340',
 '8305344',
 '8305348',
 '8305352',
 '8305356',
 '8305360',
 '11492485',
 '14310137',
 '14310141',
 '10981384',
 '14310145',
 '12804029',
 '14310149',
 '14310153',
 '11492489',
 '14310157',
 '14310161',
 '10981388',
 '14310165',
 '12804033',
 '15383069',
 '15383073',
 '8305364',
 '8305368',
 '8305372',
 '11492493',
 '8305376',
 '9658992',
 '11158137',
 '8305380',
 '8305384',
 '11158141',
 '8305392',
 '11158145',
 '8305396',
 '11492497',
 '8305400',
 '10195072',
 '11158149',
 '10195076',
 '11158153',
 '8305404',
 '11158157',
 '8305408',
 '8305412',
 '8305416',
 '8305420',
 '8305424',
 '8305428',
 '8305432',
 '8305436',
 '8921216',
 '8921220',
 '8305440',
 '8305444',
 '8305448',
 '8305452',
 '7302588',
 '8305456',
 '8305460',
 '8305464',
 '8305476',
 '14047673',
 '8305484',
 '8305488',
 '8527944',
 '8527948',
 '8305492',
 '12804037',
 '10519372',
 '15583629',
 '12804041',
 '12804045',
 '15383077',
 '8305496',
 '7096424',
 '8305500',
 '3950235',
 '8305508',
 '8305512',
 '10195080',
 '8305516',
 '8305520',
 '9658996',
 '13570065',
 '15383081',
 '15383085',
 '10454512',
 '10454516',
 '13570069',
 '8305524',
 '12804049',
 '11492501',
 '12804053',
 '12804057',
 '15383089',
 '15383093',
 '8305532',
 '10890280',
 '10890284',
 '8305536',
 '8305540',
 '8305544',
 '8305548',
 '8921228',
 '9659000',
 '8527952',
 '8305552',
 '15383097',
 '15383101',
 '12804061',
 '12804065',
 '8305572',
 '8305576',
 '8305580',
 '8305584',
 '8305588',
 '5031156',
 '8305592',
 '8305596',
 '5031159',
 '8305600',
 '8305604',
 '7096428',
 '5031162',
 '8305608',
 '7302592',
 '8305612',
 '8305616',
 '8305620',
 '8305624',
 '8305628',
 '8305632',
 '8305636',
 '8305640',
 '5031165',
 '8305644',
 '8305656',
 '8305660',
 '14912061',
 '6352956',
 '8305664',
 '8305668',
 '7075192',
 '8305672',
 '8305676',
 '8305736',
 '8305740',
 '8305744',
 '8305748',
 '8305752',
 '10110004',
 '8305756',
 '8305760',
 '8305764',
 '8305768',
 '8305772',
 '8305776',
 '8527956',
 '10454520',
 '10454524',
 '12804069',
 '15583637',
 '8305780',
 '9659004',
 '9659008',
 '8305784',
 '9722088',
 '8305792',
 '9659012',
 '12804073',
 '12804077',
 '9659016',
 '8305796',
 '10454528',
 '10454532',
 '10519376',
 '8305800',
 '10890288',
 '10519380',
 '13570073',
 '10519384',
 '13570077',
 '8305804',
 '8305808',
 '10890292',
 '10890296',
 '12804081',
 '12804085',
 '10454536',
 '10890300',
 '10890304',
 '13570081',
 '10890308',
 '13060773',
 '13570085',
 '12804089',
 '10890312',
 '12804093',
 '8305816',
 '13570089',
 '11158161',
 '8305820',
 '9659024',
 '8305824',
 '15383105',
 '15383109',
 '15383113',
 '8527960',
 '8305928',
 '8305932',
 '8305936',
 '7308108',
 '8305940',
 '9854492',
 '8305948',
 '8305952',
 '8305956',
 '12804097',
 '14047681',
 '14047685',
 '14047689',
 '15383117',
 '15383121',
 '7096432',
 '9854500',
 '8306156',
 '7096440',
 '8306200',
 '8306204',
 '3950487',
 '8715964',
 '8715968',
 '8715972',
 '8715976',
 '8715980',
 '8715984',
 '8715988',
 '8715992',
 '8715996',
 '8716000',
 '8716004',
 '8716008',
 '8716012',
 '8716016',
 '8716020',
 '8716024',
 '8716028',
 '8716032',
 '8716036',
 '8716040',
 '8716044',
 '8716048',
 '8716080',
 '8716088',
 '8716096',
 '8716104',
 '8716108',
 '8716112',
 '8716116',
 '8716120',
 '13060781',
 '9722096',
 '13060785',
 '13060789',
 '13060793',
 '13060797',
 '13572049',
 '13572053',
 '13572057',
 '13572061',
 '14047965',
 '14047969',
 '14047973',
 '14047977',
 '14047981',
 '14047985',
 '14047989',
 '14047993',
 '14047997',
 '13570149',
 '15383825',
 '13570153',
 '13570157',
 '13570161',
 '13570165',
 '15383829',
 '15383833',
 '15383837',
 '15383841',
 '15383845',
 '15383849',
 '15583693',
 '15383853']

In [3]:
crawler_status = 'error'

crawler_status

error

In [4]:
import requests

import sys
sys.path.append('../00.Tools')
import UA
import Proxy

In [7]:
a = 0

data = {'func': 'getbuyersguide',
        'payload': '{"partData":{"listing_data_essential":{"parttype":"' + input_.loc[a, 'Type_Code'] + '","partkey":"' + input_.loc[a, 'Part_Key'] + '"}}}',
        'api_json_request': '1'}

resp = requests.post('https://www.rockauto.com/catalog/catalogapi.php',
                     data=data,
                     headers=UA.get_User_Agent_Requests(),
                     proxies=Proxy.get_Proxy_Requests()).text

resp

'{"buyersguidepieces":{"body":"<div class=\\"buyersguide-nested\\"><div style=\\"padding: .5em;\\"><table class=\\"nobmp\\" style=\\"width: 100%;\\"><tr><td class=\\"altrow-a-0\\">MAZDA<\\/td><td class=\\"altrow-a-0\\">3<\\/td><td class=\\"altrow-a-0\\">2004-2007<\\/td><\\/tr><tr><td class=\\"altrow-a-1\\">MAZDA<\\/td><td class=\\"altrow-a-1\\">5<\\/td><td class=\\"altrow-a-1\\">2006-2007<\\/td><\\/tr><tr><td class=\\"altrow-a-0\\">MAZDA<\\/td><td class=\\"altrow-a-0\\">6<\\/td><td class=\\"altrow-a-0\\">2003-2007<\\/td><\\/tr><\\/table><div>Please refer to catalog for application details.<\\/div><\\/div><\\/div>","title":"Buyer\'s Guide :   Timing Chain & Component Kit"},"groupindex":null,"collected_javascript":"\\/**UQ:2648476B**\\/\\nwindow.top.parent.window[\\"_nck\\"] = \\"8LVLUxTaILBT+tLxkg8+3Ag7\\\\\\/0bbOhvn7P3rkFbL809YNOHQDmNBznFtdYfbcEUriQ0mcmy\\\\\\/TcWfcbfHTjxSwndfe2chgzy88liHO2MoAcp7wW7lek5DxawTLSg\\\\\\/DpYUwwgKwrMfy33luTNa6ddhYjxVOhF6r2MXjXLeTDNsWi4=\\";\\n"}'

In [8]:
import json

In [9]:
json_data = json.loads(resp)

json_data

{'buyersguidepieces': {'body': '<div class="buyersguide-nested"><div style="padding: .5em;"><table class="nobmp" style="width: 100%;"><tr><td class="altrow-a-0">MAZDA</td><td class="altrow-a-0">3</td><td class="altrow-a-0">2004-2007</td></tr><tr><td class="altrow-a-1">MAZDA</td><td class="altrow-a-1">5</td><td class="altrow-a-1">2006-2007</td></tr><tr><td class="altrow-a-0">MAZDA</td><td class="altrow-a-0">6</td><td class="altrow-a-0">2003-2007</td></tr></table><div>Please refer to catalog for application details.</div></div></div>',
  'title': "Buyer's Guide :   Timing Chain & Component Kit"},
 'groupindex': None,
 'collected_javascript': '/**UQ:2648476B**/\nwindow.top.parent.window["_nck"] = "8LVLUxTaILBT+tLxkg8+3Ag7\\/0bbOhvn7P3rkFbL809YNOHQDmNBznFtdYfbcEUriQ0mcmy\\/TcWfcbfHTjxSwndfe2chgzy88liHO2MoAcp7wW7lek5DxawTLSg\\/DpYUwwgKwrMfy33luTNa6ddhYjxVOhF6r2MXjXLeTDNsWi4=";\n'}

In [10]:
from bs4 import BeautifulSoup
from lxml import etree

In [11]:
soup = BeautifulSoup(json_data['buyersguidepieces']['body'], 'lxml')
html = etree.HTML(str(soup))

with open('./vehicle.html', 'w', encoding='UTF-8') as file:
    file.write(str(soup))

print(soup.prettify())

<html>
 <body>
  <div class="buyersguide-nested">
   <div style="padding: .5em;">
    <table class="nobmp" style="width: 100%;">
     <tr>
      <td class="altrow-a-0">
       MAZDA
      </td>
      <td class="altrow-a-0">
       3
      </td>
      <td class="altrow-a-0">
       2004-2007
      </td>
     </tr>
     <tr>
      <td class="altrow-a-1">
       MAZDA
      </td>
      <td class="altrow-a-1">
       5
      </td>
      <td class="altrow-a-1">
       2006-2007
      </td>
     </tr>
     <tr>
      <td class="altrow-a-0">
       MAZDA
      </td>
      <td class="altrow-a-0">
       6
      </td>
      <td class="altrow-a-0">
       2003-2007
      </td>
     </tr>
    </table>
    <div>
     Please refer to catalog for application details.
    </div>
   </div>
  </div>
 </body>
</html>

In [12]:
dict_vehicle = {}
list_tr = html.xpath('//div[contains(@class, "buyersguide-nested")]/div/table[contains(@class, "nobmp")]/tr')
for i in range(len(list_tr)):
    dict_vehicle[str(i)] = {}
    list_td = [str(_).strip() for _ in list_tr[i].xpath('./td/text()')]
    for j in range(len(list_td)):
        dict_vehicle[str(i)][str(j)] = list_td[j]

dict_vehicle

{'0': {'0': 'MAZDA', '1': '3', '2': '2004-2007'},
 '1': {'0': 'MAZDA', '1': '5', '2': '2006-2007'},
 '2': {'0': 'MAZDA', '1': '6', '2': '2003-2007'}}

In [13]:
vehicle_json = json.dumps(dict_vehicle)

vehicle_json

'{"0": {"0": "MAZDA", "1": "3", "2": "2004-2007"}, "1": {"0": "MAZDA", "1": "5", "2": "2006-2007"}, "2": {"0": "MAZDA", "1": "6", "2": "2003-2007"}}'

In [14]:
list_vehicle = []
for serial in dict_vehicle:
    vehicle = ''
    for serial_2 in dict_vehicle[serial]:
        vehicle += ' ' + dict_vehicle[serial][serial_2]
    list_vehicle.append(vehicle.strip())
    
vehicle = '\n'.join(list_vehicle)

print(vehicle)

MAZDA 3 2004-2007
MAZDA 5 2006-2007
MAZDA 6 2003-2007

In [15]:
df_temp = pd.DataFrame([{'JOIN_TCPK': input_.loc[a, 'JOIN_TCPK'],
                         'Vehcile_Json': vehicle_json,
                         'Vehcile': vehicle}])

output_correct = pd.concat([output_correct, df_temp], ignore_index=True).fillna('')

len(output_correct)

1

In [16]:
crawler_status = 'ok'

crawler_status

'ok'

In [17]:
if crawler_status == 'error':
    df_temp = pd.DataFrame([{'Type_Code': input_.loc[a, 'Type_Code'],
                             'Part_Key': input_.loc[a, 'Part_Key'],
                             'JOIN_TCPK': input_.loc[a, 'JOIN_TCPK']}])
    
    output_error = pd.concat([output_error, df_temp], ignore_index=True).fillna('')

len(output_error)

0

In [18]:
output_correct = output_correct.drop_duplicates(ignore_index=True)
output_correct = output_correct.sort_values(by=['JOIN_TCPK'], ascending=[True]).reset_index(drop=True)
output_correct.to_excel('./test_vehicle.xlsx', index=False)

output_correct

,JOIN_TCPK,Vehcile_Json,Vehcile
0,5756;8304960,"{""0"": {""0"": ""MAZDA"", ""1"": ""3"", ""2"": ""2004-2007...",MAZDA 3 2004-2007\nMAZDA 5 2006-2007\nMAZDA 6 ...

In [19]:
if len(output_error) != 0:
    output_error = output_error.drop_duplicates(ignore_index=True)
    output_error = output_error.sort_values(by=['Type_Code', 'Part_Key'], ascending=[True, True]).reset_index(drop=True)
    output_error.to_excel('./test_vehicle_error.xlsx', index=False)

output_error

Empty DataFrame
Columns: []
Index: []