In [1]:
import pandas as pd

file = pd.ExcelFile('./fuck.xlsx')

file.sheet_names

['page 1',
 'page 2',
 'page 3',
 'page 4',
 'page 5',
 'page 6',
 'page 7',
 'page 8',
 'page 9',
 'page 10',
 'page 11',
 'page 12',
 'page 13',
 'page 14',
 'page 15',
 'page 16',
 'page 17',
 'page 18',
 'page 19',
 'page 20',
 'page 21',
 'page 22',
 'page 23',
 'page 24',
 'page 25',
 'page 26',
 'page 27',
 'page 28',
 'page 29',
 'page 30',
 'page 31',
 'page 32',
 'page 33',
 'page 34',
 'page 35',
 'page 36',
 'page 37',
 'page 38']

In [2]:
list_df = []
for sheet_name in file.sheet_names:
    df = pd.read_excel(file, sheet_name=sheet_name)
    list_df.append(df)

df = pd.concat(list_df).reset_index(drop=True)

df.to_excel('./fuck_new.xlsx', index=False)

df

      Unnamed: 0    序号          4S          UAC
0            NaN     1         NaN    RD 10160C
1            NaN     2     33072.0          NaN
2            NaN     3         NaN    RD 1789SC
3            NaN     4         NaN    HA 10954C
4            NaN     5         NaN    RD 2203SC
...          ...   ...         ...          ...
1721         NaN  1739         NaN   EX 529442C
1722         NaN  1740  40039093.0          NaN
1723         NaN  1741  40038850.0          NaN
1724         NaN  1742         NaN     SW 2155C
1725         NaN  1743         NaN  GA 1524-10C

[1726 rows x 4 columns]