In [1]:
calculate = '../../file/计算表-【每日断货汇报】US-Ebay 20230110.xlsx'

In [2]:
import pandas as pd

In [3]:
table_1 = pd.read_excel(calculate, sheet_name='1_断货数据分析', header=1, usecols=[i for i in range(1, 9)]).loc[:4]

table_1

,层级,SKU 总数,在库为0（断货数）,在库1-2（干预数）,断货率,干预率,近期海运上架后断货数,近期海运上架后断货率
0,TOP1,525.0,75.0,28.0,0.142857,0.053333,41.0,0.078095
1,TOP10,3719.0,277.0,193.0,0.074482,0.051896,140.0,0.037645
2,TOP20,8446.0,438.0,578.0,0.051859,0.068435,236.0,0.027942
3,普通,36725.0,1872.0,4199.0,0.050973,0.114336,952.0,0.025922
4,总数,49415.0,2662.0,4998.0,0.053870,0.101143,1369.0,0.027704

In [4]:
table_2 = pd.read_excel(calculate, sheet_name='1_断货数据分析', header=1, usecols=[i for i in range(10, 17)]).loc[:4]

table_2

    层级.1  在库为0（断货）  断货无在途        占比  在库1-2（干预）   干预无在途      占比.1
0   TOP1      75.0   24.0  0.320000       28.0     5.0  0.178571
1  TOP10     277.0   95.0  0.342960      193.0    42.0  0.217617
2  TOP20     438.0  153.0  0.349315      578.0   164.0  0.283737
3     普通    1872.0  563.0  0.300748     4199.0  1679.0  0.399857
4     总数    2662.0  835.0  0.313674     4998.0  1890.0  0.378151

In [5]:
table_3 = pd.read_excel(calculate, sheet_name='1_断货数据分析', header=1, usecols=[i for i in range(18, 27)]).loc[:4]

table_3

    层级.2     W44     W45     W46     W47     W48     W49     W01  W02\n01/10
0   TOP1    44.0    49.0    60.0    47.0    47.0    47.0    63.0        75.0
1  TOP10   182.0   215.0   247.0   223.0   215.0   172.0   245.0       277.0
2  TOP20   475.0   515.0   542.0   414.0   404.0   314.0   362.0       438.0
3     普通  1440.0  1516.0  1808.0  1447.0  1412.0  1488.0  1514.0      1872.0
4     总数  2141.0  2295.0  2657.0  2131.0  2078.0  2021.0  2184.0      2662.0

In [6]:
table_4 = pd.read_excel(calculate, sheet_name='1_断货数据分析', header=1, usecols=[i for i in range(28, 33)], index_col=0)

table_4

          品类  断货SKU数量  总SKU数      断货占比
排名
TOP1      HB      387   1128  0.343085
TOP2      BC      226   2787  0.081091
TOP3      WR      137   1888  0.072564
TOP4     ABS      124   1421  0.087262
TOP5      GS      102   1313  0.077685
...      ...      ...    ...       ...
TOP378   AEV        0    299  0.000000
TOP379  BRPS        0    332  0.000000
TOP380   BRR        0    388  0.000000
TOP381   EAF        0    624  0.000000
TOP382   BHH        0   2652  0.000000

[382 rows x 4 columns]

In [7]:
sheet_2_left = pd.read_excel(calculate, sheet_name='2_断货SKU', header=1, usecols=[i for i in range(5)], index_col=0)

sheet_2_left

               SKU     层级    周销  在途
序号
1     USACC10856-C   TOP1  1.25   0
2     USACC57328-C   TOP1  1.00   0
3    USACC58333S-C   TOP1  3.50   0
4     USACC67661-C   TOP1  4.24   0
5     USACC68184-C   TOP1  4.10   0
..             ...    ...   ...  ..
278      USTS27873  TOP20  0.00   0
279      USWP04000  TOP20  2.40   0
280      USWP72360  TOP20  1.70   0
281      USWR41021  TOP20  1.00   0
282     USWS22121X  TOP20  1.00   0

[282 rows x 4 columns]

In [8]:
sheet_2_right = pd.read_excel(calculate, sheet_name='2_断货SKU', header=1, usecols=[i for i in range(7, 9)], index_col=0).dropna().sort_values(by=['断货数'], ascending=False)

sheet_2_right

        断货数
品类去重
ACC    49.0
HB     30.0
ALT    17.0
IM     10.0
CA     10.0
DC      8.0
PSR     8.0
SA      8.0
CON     7.0
KS      7.0
STR     7.0
DS      7.0
BT      7.0
CVA     6.0
RAD     6.0
BC      6.0
THB     5.0
OP      5.0
PSP     4.0
OIP     4.0
HCR     4.0
BM      4.0
WP      4.0
WR      4.0
ICK     4.0
FP      3.0
TBC     3.0
HBZ     3.0
PTB     2.0
RBM     2.0
PBB     2.0
SKA     2.0
ABS     2.0
GS      2.0
AST     2.0
AIH     2.0
CS-弹簧   2.0
CSP     2.0
ACH     1.0
VCS     1.0
TSS     1.0
TS      1.0
TPMS    1.0
ASM     1.0
THA     1.0
TCV     1.0
TCM     1.0
BMR     1.0
BDA     1.0
MAF     1.0
SDR     1.0
CHC     1.0
COV     1.0
EM      1.0
ET      1.0
PHLS    1.0
ETC     1.0
FIC     1.0
GPR     1.0
WS      1.0

In [9]:
print(int(table_1.loc[4, '在库为0（断货数）']), end='; ')
print(str(table_1.loc[4, '断货率']*100).split('.')[0] + '.' + str(round(table_1.loc[4, '断货率']*10000) - int(str(table_1.loc[4, '断货率']*100).split('.')[0])*100) + '%', end='; ')
print(table_1.loc[table_1['断货率'].tolist().index(max(table_1['断货率'])), '层级'], end='; ')
print(str(max(table_1['断货率'])*100).split('.')[0] + '.' + str(round(max(table_1['断货率'])*10000) - int(str(max(table_1['断货率'])*100).split('.')[0])*100) + '%', end='; ')
print(table_1.loc[table_1['干预率'].tolist().index(max(table_1['干预率'])), '层级'], end='; ')
print(str(max(table_1['干预率'])*100).split('.')[0] + '.' + str(round(max(table_1['干预率'])*10000) - int(str(max(table_1['干预率'])*100).split('.')[0])*100) + '%')
print('\n= = = = = = = = = = = = = = = = = =\n')
print(len(sheet_2_left), end='; ')
print(sheet_2_right['断货数'].index[0], end='; ')
print(sheet_2_right['断货数'].index[1], end='; ')
print(sheet_2_right['断货数'].index[2], end='; ')
print(int(sheet_2_right.iloc[0, 0]), end='; ')
print(int(sheet_2_right.iloc[1, 0]), end='; ')
print(int(sheet_2_right.iloc[2, 0]))
print('\n= = = = = = = = = = = = = = = = = =\n')
print(len(sheet_2_left[sheet_2_left['层级']=='TOP1']))

2662; 5.39%; TOP1; 14.29%; 普通; 11.43%

= = = = = = = = = = = = = = = = = =

282; ACC; HB; ALT; 49; 30; 17

= = = = = = = = = = = = = = = = = =

25

In [10]:
print(int(table_2.loc[4, '在库为0（断货）']), end='; ')
print(int(table_2.loc[4, '断货无在途']), end='; ')
print(str(table_2.loc[4, '占比']*100).split('.')[0] + '.' + str(round(table_2.loc[4, '占比']*10000) - int(str(table_2.loc[4, '占比']*100).split('.')[0])*100) + '%', end='; ')
print(int(table_2.loc[4, '在库1-2（干预）']), end='; ')
print(int(table_2.loc[4, '干预无在途']), end='; ')
print(str(table_2.loc[4, '占比.1']*100).split('.')[0] + '.' + str(round(table_2.loc[4, '占比.1']*10000) - int(str(table_2.loc[4, '占比.1']*100).split('.')[0])*100) + '%')
print('\n= = = = = = = = = = = = = = = = = =\n')
print(int(table_2.loc[0, '在库1-2（干预）']), end='; ')
print(int(table_2.loc[0, '干预无在途']))

2662; 835; 31.37%; 4998; 1890; 37.82%

= = = = = = = = = = = = = = = = = =

28; 5

In [11]:
print('TOP1: ' + str(int(table_3.iloc[0, 8] - table_3.iloc[0, 7])))
print('TOP10: ' + str(int(table_3.iloc[1, 8] - table_3.iloc[1, 7])))
print('TOP20: ' + str(int(table_3.iloc[2, 8] - table_3.iloc[2, 7])))
print('普通: ' + str(int(table_3.iloc[3, 8] - table_3.iloc[3, 7])))

TOP1: 12
TOP10: 32
TOP20: 76
普通: 358

In [12]:
print(table_4.loc['TOP1', '品类'], end='; ')
print(table_4.loc['TOP1', '断货SKU数量'])
print('\n= = = = = = = = = = = = = = = = = =\n')
print(table_4.iloc[table_4['断货占比'][:10].tolist().index(max(table_4['断货占比'][:10])), 0], end='; ')
print(table_4.iloc[table_4['断货占比'][:10].tolist().index(max(table_4['断货占比'][:10])), 2], end='; ')
print(str(max(table_4['断货占比'][:10])*100).split('.')[0] + '.' + str(round(max(table_4['断货占比'][:10])*10000) - int(str(max(table_4['断货占比'][:10])*100).split('.')[0])*100) + '%')

HB; 387

= = = = = = = = = = = = = = = = = =

HB; 1128; 34.31%