- Update: 2023.02.07

# 0. 配置参数

- `calculate`：what the fuck

In [1]:
calculate = '../../file/计算表-【每日断货汇报】US-Ebay 20230207.xlsx'

out = '../../file/Lennon_断货汇报_筛选好的断货SKU_NOW().xlsx'

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(calculate, sheet_name='附_1统计源（含新品、清仓、新品成长）', header=3, usecols=[i for i in range(1, 13)])

df

,No.,MRP SKU,目标\n周销,品类,Level,状态变更日,状态,运营备注,未售出周数,注意事项,在库,在途
0,1,USGS06060Z,36.1,GS,TOP10,2021-06-27,老品,暴涨,0,NaN,323.0,265
1,2,USOFA294AEB-C,15.9,OFA,TOP1,2021-07-11,老品,NaN,0,调整周销,88.0,188
2,3,USET03102H,25.5,ET,TOP1,2020-07-05,老品,暴涨,0,NaN,487.0,200
3,4,USGSM3570T,25.7,GS,TOP10,2022-03-14,老品,暴涨,0,更新周销,33.0,165
4,5,USSGUN004-4BZ,20.2,SG,TOP1,2021-01-24,老品,NaN,0,更新周销,142.0,164
...,...,...,...,...,...,...,...,...,...,...,...,...
50371,50372,USWR51690,1.0,WR,TOP20,2023-01-30,新品,NaN,0,NaN,NaN,3
50372,50373,USWR51691,1.0,WR,TOP20,2023-01-30,新品,NaN,0,NaN,NaN,3
50373,50374,USWR71001,1.0,WR,普通,2023-01-30,新品,NaN,0,NaN,NaN,3
50374,50375,USWR75001,1.0,WR,普通,2023-01-30,新品,NaN,0,NaN,NaN,3
50375,50376,USBDA04282,0.5,BDA,普通,2023-02-06,断货,NaN,0,NaN,NaN,0

In [4]:
df = df[(df['在库']==0) & (df['在途']==0) & (df['Level']!='普通')][['MRP SKU', 'Level', '目标\n周销', '在途']]

df

              MRP SKU  Level  目标\n周销  在途
41          USGSM3269  TOP20   19.00   0
992        USSKA186BA  TOP10    3.10   0
1226       USALT23992  TOP10    1.70   0
1859   USHB28001S-2-C  TOP10    1.01   0
1966        USOS25086  TOP10    3.60   0
...               ...    ...     ...  ..
49791   USTCTOS008-YC  TOP20    1.00   0
49797   USTCTOS006-YC  TOP10    2.00   0
49874    USCAF11182-C  TOP20   10.00   0
49888    USCAF10373-C  TOP20    7.00   0
49902    USCAF58440-C  TOP20    5.00   0

[182 rows x 4 columns]

In [5]:
import datetime

writer = pd.ExcelWriter(out.replace('NOW()', datetime.datetime.now().strftime("%Y%m%d_%H%M%S")))
df.to_excel(writer, index=False)
writer.close()