- Update: 2023.02.04

# 0. 配置参数

- `alternate`：替代料总表路径
- `mrp`：MRP表路径
- `temp_out`：保存结果的路径
- `out`：保存结果的路径

In [1]:
alternate = '../../file/替代料总表01-30.xlsx'
mrp = '../../file/US MRP20230130运营.xlsx'

temp_out = '../../file/Lennon_断货汇报_temp替代料表_NOW().xlsx'
out = '../../file/Lennon_断货汇报_整理好的替代料表_NOW().xlsx'

In [2]:
import pandas as pd

In [3]:
temp_df_alternate = pd.read_excel(alternate, sheet_name='MRP SKU库存', header=1)[['主料SKU', '替换料1', '替换料2', '替换料3', '替换料4', '替换料5', '替换料6']].fillna('')

temp_df_alternate

                 主料SKU           替换料1          替换料2        替换料3 替换料4 替换料5 替换料6
0        USCA171876D-3    USCA171876D  USCA171876-3  USCA171876
1           USBDA04108  USBDA04108X-C
2           USGS43640B      USGS43640
3            USWS02863
4            USWS02632
...                ...            ...           ...         ...  ...  ...  ...
49995      USBM10143-C
49996  USFM0TO019B0-YC
49997  USFM0TO018B0-YC
49998  USFM0TO017B0-YC
49999       USCAK03420

[50000 rows x 7 columns]

In [4]:
df_mrp = pd.read_excel(mrp, header=1)[['MRP SKU']]

df_mrp

                 MRP SKU
0             USGS06060Z
1      USTCV17215HIE-2-C
2           USTBC40007-C
3             USGS41420B
4             USGSM3570T
...                  ...
49913    USFM0FD006B0-YC
49914         USASV98007
49915         USASC3B484
49916         USCAK53670
49917         USCAK03420

[49918 rows x 1 columns]

# 1. 调整替代料表

In [5]:
temp_df_alternate = pd.merge(left=temp_df_alternate, right=df_mrp, how='left', left_on='主料SKU', right_on='MRP SKU').fillna('')
temp_df_alternate = pd.merge(left=temp_df_alternate, right=df_mrp, how='left', left_on='替换料1', right_on='MRP SKU', suffixes=('', '_1')).fillna('')
temp_df_alternate = pd.merge(left=temp_df_alternate, right=df_mrp, how='left', left_on='替换料2', right_on='MRP SKU', suffixes=('', '_2')).fillna('')
temp_df_alternate = pd.merge(left=temp_df_alternate, right=df_mrp, how='left', left_on='替换料3', right_on='MRP SKU', suffixes=('', '_3')).fillna('')
temp_df_alternate = pd.merge(left=temp_df_alternate, right=df_mrp, how='left', left_on='替换料4', right_on='MRP SKU', suffixes=('', '_4')).fillna('')
temp_df_alternate = pd.merge(left=temp_df_alternate, right=df_mrp, how='left', left_on='替换料5', right_on='MRP SKU', suffixes=('', '_5')).fillna('')
temp_df_alternate = pd.merge(left=temp_df_alternate, right=df_mrp, how='left', left_on='替换料6', right_on='MRP SKU', suffixes=('', '_6')).fillna('')
temp_df_alternate['MRP SKU'] = ['' if i == '' else '0' for i in temp_df_alternate['MRP SKU']]
temp_df_alternate['MRP SKU_1'] = ['' if i == '' else '1' for i in temp_df_alternate['MRP SKU_1']]
temp_df_alternate['MRP SKU_2'] = ['' if i == '' else '2' for i in temp_df_alternate['MRP SKU_2']]
temp_df_alternate['MRP SKU_3'] = ['' if i == '' else '3' for i in temp_df_alternate['MRP SKU_3']]
temp_df_alternate['MRP SKU_4'] = ['' if i == '' else '4' for i in temp_df_alternate['MRP SKU_4']]
temp_df_alternate['MRP SKU_5'] = ['' if i == '' else '5' for i in temp_df_alternate['MRP SKU_5']]
temp_df_alternate['MRP SKU_6'] = ['' if i == '' else '6' for i in temp_df_alternate['MRP SKU_6']]

temp_df_alternate

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,MRP SKU,MRP SKU_1,MRP SKU_2,MRP SKU_3,MRP SKU_4,MRP SKU_5,MRP SKU_6
0,USCA171876D-3,USCA171876D,USCA171876-3,USCA171876,,,,0,,,,,,
1,USBDA04108,USBDA04108X-C,,,,,,0,,,,,,
2,USGS43640B,USGS43640,,,,,,0,,,,,,
3,USWS02863,,,,,,,0,,,,,,
4,USWS02632,,,,,,,0,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,USBM10143-C,,,,,,,0,,,,,,
49996,USFM0TO019B0-YC,,,,,,,0,,,,,,
49997,USFM0TO018B0-YC,,,,,,,0,,,,,,
49998,USFM0TO017B0-YC,,,,,,,0,,,,,,
49999,USCAK03420,,,,,,,0,,,,,,

In [6]:
import re

In [7]:
list_note = ';' + temp_df_alternate['MRP SKU'] + ';' + temp_df_alternate['MRP SKU_1'] + ';' + temp_df_alternate['MRP SKU_2'] + ';' + temp_df_alternate['MRP SKU_3'] + ';' + temp_df_alternate['MRP SKU_4'] + ';' + temp_df_alternate['MRP SKU_5'] + ';' + temp_df_alternate['MRP SKU_6'] + ';'
temp_df_alternate['note'] = [re.sub(r';{2,}', ';', i)[1:-1] for i in list_note]
temp_df_alternate = temp_df_alternate[['主料SKU', '替换料1', '替换料2', '替换料3', '替换料4', '替换料5', '替换料6', 'note']]

temp_df_alternate

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,note
0,USCA171876D-3,USCA171876D,USCA171876-3,USCA171876,,,,0
1,USBDA04108,USBDA04108X-C,,,,,,0
2,USGS43640B,USGS43640,,,,,,0
3,USWS02863,,,,,,,0
4,USWS02632,,,,,,,0
...,...,...,...,...,...,...,...,...
49995,USBM10143-C,,,,,,,0
49996,USFM0TO019B0-YC,,,,,,,0
49997,USFM0TO018B0-YC,,,,,,,0
49998,USFM0TO017B0-YC,,,,,,,0
49999,USCAK03420,,,,,,,0

In [8]:
df_0 = temp_df_alternate[temp_df_alternate['note'] == '0']

df_0

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,note
0,USCA171876D-3,USCA171876D,USCA171876-3,USCA171876,,,,0
1,USBDA04108,USBDA04108X-C,,,,,,0
2,USGS43640B,USGS43640,,,,,,0
3,USWS02863,,,,,,,0
4,USWS02632,,,,,,,0
...,...,...,...,...,...,...,...,...
49995,USBM10143-C,,,,,,,0
49996,USFM0TO019B0-YC,,,,,,,0
49997,USFM0TO018B0-YC,,,,,,,0
49998,USFM0TO017B0-YC,,,,,,,0
49999,USCAK03420,,,,,,,0

In [9]:
df_1 = temp_df_alternate[(temp_df_alternate['note'] == '1') | (temp_df_alternate['note'] == '2') | (temp_df_alternate['note'] == '3') | (temp_df_alternate['note'] == '4') | (temp_df_alternate['note'] == '5') | (temp_df_alternate['note'] == '6')].reset_index(drop=True)

df_1

           主料SKU          替换料1         替换料2       替换料3 替换料4 替换料5 替换料6 note
0     USBDA04106   USBDA04106X                                           1
1     USBDA04120   USBDA04120X                                           1
2     USBDA04205   USBDA04205X                                           1
3     USBDA04101   USBDA04101X                                           1
4     USBDA04209   USBDA04209X                                           1
5     USBDA04111   USBDA04111X                                           1
6    USFP2388M0Z    USFP2388M0                                           1
7    USFP2453M0Z    USFP2453M0                                           1
8    USFP3701M0Z    USFP3701M0                                           1
9    USFP3749M0Z    USFP3749M0                                           1
10   USFP3804M0Z    USFP3804M0                                           1
11   USFP6693M0Z    USFP6693M0                                           1
12   USFP8470M0Z    USFP8470M0  USFP8470M0H                              2
13   USFP8642M0Z    USFP8642M0                                           1
14   USFP8808M0Z    USFP8808M0                                           1
15     USKS98016    USKS98016L                                           1
16     USKS98064    USKS98064L                                           1
17   USFP7173M0Z    USFP7173M0                                           1
18     USKS98302    USKS98302L                                           1
19   USKS98303LR  USKS98303LLR                                           1
20     USKS98303    USKS98303L                                           1
21  USBCB92861AZ   USBCB92861A                                           1
22  USBCB92860AZ   USBCB92860A                                           1
23   USOPK3600DF    USOPK3600D   USOP3600DF  USOP3600D                   3
24    USKS98112L     USKS98112                                           1
25    USKS98113L     USKS98113                                           1
26  USKS98113LLR   USKS98113LR                                           1
27     USKS98107    USKS98107L                                           1
28     USKS98106    USKS98106L                                           1
29    USKS98001L     USKS98001                                           1

In [10]:
df_2_1 = temp_df_alternate[(temp_df_alternate['note'] == '0;1') | (temp_df_alternate['note'] == '0;2')].reset_index(drop=True)
df_2_2 = df_2_1.copy()

df_2_1

          主料SKU        替换料1         替换料2       替换料3        替换料4 替换料5 替换料6 note
0    USWR589RLC   USWR589RL                                                0;1
1    USGS66110B   USGS66110  USGS66110BS                                   0;2
2     USCA71934  USCAK20801                                                0;1
3    USWR590RRC   USWR590RR                                                0;1
4    USCAK20801   USCA71934                                                0;1
5   USWR52641MU  USWR52641M    USWR52641                                   0;2
6  USWR832FRJHY  USWR832FRJ    USWR832FR  USWR41832  USWR41832J            0;2
7  USDIF41300-C  USDIF41300                                                0;1
8    USIC26800L   USIC26800     USIC6D10                                   0;2

In [11]:
for i in range(len(df_2_1)):
    list_note = df_2_1.loc[i, 'note'].split(';')
    # 依次向前，去除这个SKU且保留后面的全部
    for j in range(int(list_note[1]), 6):
        df_2_1.loc[i, '替换料' + str(j)] = df_2_1.loc[i, '替换料' + str(j+1)]

df_0 = pd.concat([df_0, df_2_1]).reset_index(drop=True)

df_0

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,note
0,USCA171876D-3,USCA171876D,USCA171876-3,USCA171876,,,,0
1,USBDA04108,USBDA04108X-C,,,,,,0
2,USGS43640B,USGS43640,,,,,,0
3,USWS02863,,,,,,,0
4,USWS02632,,,,,,,0
...,...,...,...,...,...,...,...,...
49913,USCAK20801,,,,,,,0;1
49914,USWR52641MU,USWR52641M,,,,,,0;2
49915,USWR832FRJHY,USWR832FRJ,USWR41832,USWR41832J,,,,0;2
49916,USDIF41300-C,,,,,,,0;1
49917,USIC26800L,USIC26800,,,,,,0;2

In [12]:
for i in range(len(df_1)):
    if df_1.loc[i, '替换料' + df_1.loc[i, 'note']] not in df_0['主料SKU'].tolist():
        # 主元法：直接把不在MRP表中的主料SKU和在MRP表中的替换料x进行调换
        df_1.loc[i, '主料SKU'], df_1.loc[i, '替换料' + df_1.loc[i, 'note']] = df_1.loc[i, '替换料' + df_1.loc[i, 'note']], df_1.loc[i, '主料SKU']
        df_0 = pd.concat(df_0, df_1.loc[[i]]).reset_index(drop=True)

df_0

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,note
0,USCA171876D-3,USCA171876D,USCA171876-3,USCA171876,,,,0
1,USBDA04108,USBDA04108X-C,,,,,,0
2,USGS43640B,USGS43640,,,,,,0
3,USWS02863,,,,,,,0
4,USWS02632,,,,,,,0
...,...,...,...,...,...,...,...,...
49913,USCAK20801,,,,,,,0;1
49914,USWR52641MU,USWR52641M,,,,,,0;2
49915,USWR832FRJHY,USWR832FRJ,USWR41832,USWR41832J,,,,0;2
49916,USDIF41300-C,,,,,,,0;1
49917,USIC26800L,USIC26800,,,,,,0;2

In [13]:
for i in range(len(df_2_2)):
    list_note = df_2_2.loc[i, 'note'].split(';')
    # 先查重，不重复就添加
    if df_2_2.loc[i, '替换料' + list_note[1]] not in df_0['主料SKU'].tolist():
        df_0 = pd.concat(df_0, pd.DataFrame({'主料SKU': [df_2_2.loc[i, '替换料' + list_note[1]]],
                                             '替换料1': [''],
                                             '替换料2': [''],
                                             '替换料3': [''],
                                             '替换料4': [''],
                                             '替换料5': [''],
                                             '替换料6': ['']})).reset_index(drop=True)

df_0

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,note
0,USCA171876D-3,USCA171876D,USCA171876-3,USCA171876,,,,0
1,USBDA04108,USBDA04108X-C,,,,,,0
2,USGS43640B,USGS43640,,,,,,0
3,USWS02863,,,,,,,0
4,USWS02632,,,,,,,0
...,...,...,...,...,...,...,...,...
49913,USCAK20801,,,,,,,0;1
49914,USWR52641MU,USWR52641M,,,,,,0;2
49915,USWR832FRJHY,USWR832FRJ,USWR41832,USWR41832J,,,,0;2
49916,USDIF41300-C,,,,,,,0;1
49917,USIC26800L,USIC26800,,,,,,0;2

In [14]:
df_0 = df_0[['主料SKU', '替换料1', '替换料2', '替换料3', '替换料4', '替换料5', '替换料6']]

df_0

               主料SKU           替换料1          替换料2        替换料3 替换料4 替换料5 替换料6
0      USCA171876D-3    USCA171876D  USCA171876-3  USCA171876
1         USBDA04108  USBDA04108X-C
2         USGS43640B      USGS43640
3          USWS02863
4          USWS02632
...              ...            ...           ...         ...  ...  ...  ...
49913     USCAK20801
49914    USWR52641MU     USWR52641M
49915   USWR832FRJHY     USWR832FRJ     USWR41832  USWR41832J
49916   USDIF41300-C
49917     USIC26800L      USIC26800

[49918 rows x 7 columns]

# 2. 保存

In [15]:
import datetime

writer = pd.ExcelWriter(temp_out.replace('NOW()', datetime.datetime.now().strftime("%Y%m%d_%H%M%S")))
temp_df_alternate.to_excel(writer, index=False)
writer.close()
writer = pd.ExcelWriter(out.replace('NOW()', datetime.datetime.now().strftime("%Y%m%d_%H%M%S")))
df_0.to_excel(writer, index=False)
writer.close()