In [1]:
import pandas as pd

In [2]:
df_category = pd.read_excel('./category.xlsx',
                            header=0,
                            dtype=str).fillna('')

df_category

,Category_No.,Category,Url
0,1,Accessories,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
1,2,Suits Audi,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
2,3,Suits BMW,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
3,4,Suits Chevrolet (Chevy),https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
4,5,Suits Citroen,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
5,6,Suits Daewoo,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
6,7,Suits Fiat,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
7,8,Suits Ford,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
8,9,Suits Hino,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
9,10,Suits Holden,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
10,11,Suits Honda,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
11,12,Suits Hyundai,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
12,13,Suits Isuzu,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
13,14,Suits Iveco,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
14,15,Suits Jeep,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
15,16,Suits Kia,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
16,17,Suits Land Rover,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
17,18,Suits Lexus,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
18,19,Suits Mazda,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
19,20,Suits Mercedes Benz,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
20,21,Suits Mitsubishi,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
21,22,Suits Nissan,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
22,23,Suits Opel,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
23,24,Suits Peugeot,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
24,25,Suits Renault,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
25,26,Suits Skoda,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
26,27,Suits Subaru,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
27,28,Suits Suzuki,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
28,29,Suits Toyota,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
29,30,Suits Volkswagen,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...
30,31,Other,https://www.ebay.com.au/sch/i.html?_dkr=1&icon...

In [3]:
df_menu = pd.DataFrame()

df_menu

Empty DataFrame
Columns: []
Index: []

In [4]:
from tqdm import tqdm
import os
import json

In [5]:
for i in tqdm(range(len(df_category)), desc='Progress', ncols=77):
    list_file = list(os.walk('./category/' + df_category.loc[i, 'Category_No.']))[0][2]
    if '.DS_Store' in list_file:
        list_file.remove('.DS_Store')
    if '0.null.txt' in list_file:
        list_file.remove('0.null.txt')

    list_file.sort()
    
    for file in list_file:
        with open('./category/' + df_category.loc[i, 'Category_No.'] + '/' + file, 'r', encoding='UTF-8') as f:
            df_temp = pd.DataFrame(json.loads(f.read()))
            df_temp['Category_No.'] = int(df_category.loc[i, 'Category_No.'])
            df_temp['Category'] = df_category.loc[i, 'Category']
            df_menu = pd.concat([df_menu, df_temp], ignore_index=False).fillna('')
            
df_menu.to_excel('./menu.xlsx', index=False)
            
df_menu

Progress: 100%|█████████████████████████████| 31/31 [00:00<00:00, 226.50it/s]

     Page    No.   Item_Number  Category_No.     Category
0     1.0    1.0  142846318354             1  Accessories
1     1.0    2.0  141974393891             1  Accessories
2     1.0    3.0  141974393887             1  Accessories
3     1.0    4.0  142330872739             1  Accessories
4     1.0    5.0  142695105081             1  Accessories
..    ...    ...           ...           ...          ...
235   9.0  236.0  143782708981            31        Other
236   9.0  237.0  145303392641            31        Other
237   9.0  238.0  145303395829            31        Other
238   9.0  239.0  143219471331            31        Other
239   9.0  240.0  143219596681            31        Other

[11147 rows x 5 columns]