In [1]:
import requests
import json

import sys
sys.path.append('../00.Tools')
from crawler_configuration import get_header, get_proxy

data = {'getAPIKeyForUser': {'catalog': 'tecdocsw',
                             'username': '186299u15',
                             'password': 'APMTeDoW14'}}

b = 0
while True:
    b += 1
    print(b)
    try:
        resp = requests.post('https://webservice.tecalliance.services/webcat30/v1/services/WebCat30WS.jsonEndpoint',
                             data=json.dumps(data),
                             headers=get_header(),
                             #proxies=get_proxy(),
                             timeout=(10, 10))

        if resp.status_code == 200:
            json_ = resp.json()

            if json_['status'] == 200:
                key = json_['apiKey']
                break
    except KeyboardInterrupt:
        break
    except:
        continue

key

1

'2BeBXg69osbuG45Rjtv1wLEnHL3nuT3WTRquxK1kr7CydjXY7oG4'

In [2]:
import os

list_file = sorted(list(os.walk('./file/2.part'))[0][2])
while '.DS_Store' in list_file:
    list_file.remove('.DS_Store')
while '0.null.txt' in list_file:
    list_file.remove('0.null.txt')

list_file

['crawler_1.xlsx', 'crawler_2.xlsx']

In [3]:
file = list_file[0]

file

'crawler_1.xlsx'

In [4]:
import pandas as pd

output_correct, output_error = pd.DataFrame(), pd.DataFrame()

In [7]:
input_ = pd.read_excel(f'./file/2.part/{file}',
                       header=0,
                       dtype=str).fillna('')

input_['No'] = input_['No'].astype(int)

print(f'总数量：{len(input_)}')
input_['Part Code'].tolist()

总数量：1900

['44173537',
 '44173544',
 '44173550',
 '44173554',
 '44173563',
 '44223724',
 '44224573',
 '44289437',
 '44289976',
 '44291119',
 '44291595',
 '44342707',
 '44343931',
 '44352031',
 '44353383',
 '44353689',
 '44353786',
 '44354011',
 '44354083',
 '44354099',
 '44356443',
 '44359580',
 '44359763',
 '44359974',
 '44360059',
 '44360060',
 '44361579',
 '44369923',
 '44380212',
 '44400565',
 '44404675',
 '44404781',
 '44542273',
 '44555971',
 '44556037',
 '44600558',
 '44608524',
 '44610959',
 '44635022',
 '44655011',
 '44662219',
 '44673850',
 '44683866',
 '44694186',
 '44694297',
 '44694332',
 '44694430',
 '44694591',
 '44694669',
 '44695203',
 '44695482',
 '44695817',
 '44702461',
 '44702506',
 '44728921',
 '935984792',
 '44729230',
 '44754844',
 '44754846',
 '44765003',
 '44777419',
 '44777423',
 '44777428',
 '44777429',
 '44777431',
 '44777433',
 '44777439',
 '44810354',
 '44810883',
 '44819543',
 '44819545',
 '44819539',
 '44820525',
 '44820539',
 '44830690',
 '44832430',
 '44833254',
 '44833257',
 '44833446',
 '44949013',
 '44960918',
 '44964090',
 '44964091',
 '44964094',
 '44964097',
 '44969498',
 '44977173',
 '44977168',
 '45079075',
 '45079070',
 '45126812',
 '45193948',
 '45217648',
 '45223593',
 '45238765',
 '45239247',
 '45500026',
 '45500223',
 '45500239',
 '45720921',
 '45720990',
 '45721126',
 '45721613',
 '45722005',
 '45722440',
 '45723367',
 '45723731',
 '45723863',
 '45723945',
 '45724517',
 '45724565',
 '45724715',
 '45724800',
 '45724868',
 '45726285',
 '45726674',
 '45726719',
 '45726921',
 '45806333',
 '45833638',
 '45834584',
 '45834743',
 '45837592',
 '45853520',
 '45853542',
 '45860958',
 '45860999',
 '45862145',
 '45862189',
 '45862232',
 '45987010',
 '45987614',
 '45989870',
 '45989979',
 '45990501',
 '45990568',
 '45995188',
 '46018023',
 '46018019',
 '46035985',
 '46041328',
 '46078456',
 '1444587405',
 '46104216',
 '46104553',
 '46143386',
 '46143813',
 '46143817',
 '46143821',
 '46156152',
 '46164740',
 '46164763',
 '46175044',
 '46175336',
 '46192649',
 '46199877',
 '46201437',
 '249187355',
 '46217633',
 '237588414',
 '237588600',
 '237590663',
 '249190329',
 '237593863',
 '237593864',
 '249190451',
 '249191025',
 '254607788',
 '46219372',
 '249193133',
 '249193130',
 '264641510',
 '264648883',
 '264648881',
 '264649955',
 '264653025',
 '264661582',
 '264661598',
 '740203450',
 '264661642',
 '46224489',
 '46224724',
 '46227759',
 '1343725783',
 '278301764',
 '278301746',
 '278301741',
 '278301749',
 '278301750',
 '278301743',
 '1463971103',
 '309119756',
 '309119757',
 '46232659',
 '300140494',
 '300140698',
 '300140733',
 '300140753',
 '300140776',
 '300140805',
 '300140948',
 '300140975',
 '300141139',
 '300141211',
 '300141287',
 '46234557',
 '300141635',
 '46234554',
 '46234562',
 '309138364',
 '309138365',
 '309138366',
 '309138504',
 '322760439',
 '1464003339',
 '309140992',
 '309146313',
 '309147225',
 '309151655',
 '436410002',
 '1464012353',
 '309151676',
 '1464012406',
 '1464012424',
 '322765520',
 '322769100',
 '337226228',
 '322769106',
 '322769107',
 '322769108',
 '322769109',
 '322769110',
 '322769119',
 '347238334',
 '1464012786',
 '322769236',
 '322769261',
 '322769265',
 '337227892',
 '337236284',
 '379575061',
 '337236545',
 '337236549',
 '337238475',
 '337240201',
 '347242236',
 '347243077',
 '347243082',
 '459861850',
 '357865349',
 '357865400',
 '369789496',
 '369789504',
 '369789609',
 '357866808',
 '369789724',
 '357867127',
 '357867135',
 '357867139',
 '369789730',
 '369789802',
 '357867164',
 '357867170',
 '357867183',
 '357867188',
 '369789815',
 '357867235',
 '369789878',
 '369792732',
 '369796872',
 '369797643',
 '369797759',
 '369798361',
 '369798628',
 '369801248',
 '369801282',
 '401571719',
 '46243494',
 '369801316',
 '369801913',
 '390976578',
 '379610206',
 '401581412',
 '390981157',
 '390981170',
 '401583374',
 '401583422',
 '427506691',
 '427506712',
 '427506723',
 '401590321',
 '401590771',
 '411376042',
 '484987999',
 '411378688',
 '411378728',
 '411378767',
 '411378784',
 '484988097',
 '411378837',
 '411378854',
 '427513507',
 '411381206',
 '411382186',
 '411385925',
 '401606448',
 '401606454',
 '401606475',
 '401606508',
 '401606529',
 '411385967',
 '411386008',
 '411386025',
 '411386030',
 '411386059',
 '1343788432',
 '401606537',
 '411386428',
 '411386472',
 '411386515',
 '411386538',
 '411386556',
 '411386560',
 '411386571',
 '411386575',
 '411386582',
 '411386592',
 '411386612',
 '427514358',
 '411386632',
 '411386652',
 '411386673',
 '411386683',
 '484988300',
 '484988305',
 '484988308',
 '484988312',
 '1464085209',
 '411386829',
 '411386881',
 '411387225',
 '411391713',
 '411391722',
 '427529310',
 '427529331',
 '427529352',
 '427530696',
 '436433497',
 '436434497',
 '436434510',
 '436434513',
 '436434523',
 '436434541',
 '1464096136',
 '446755192',
 '629053747',
 '436437606',
 '436439720',
 '436439736',
 '436440543',
 '436440549',
 '436440552',
 '436451132',
 '436451147',
 '436451201',
 '436459098',
 '436459106',
 '436459121',
 '436459133',
 '436459143',
 '436459149',
 '436459158',
 '436459371',
 '436459393',
 '436459396',
 '436459399',
 '446769789',
 '446769841',
 '446770032',
 '446770315',
 '446770343',
 '1243695184',
 '526595037',
 '446773228',
 '446773378',
 '446773462',
 '446773487',
 '1464134630',
 '459907071',
 '459907096',
 '459907298',
 '459908215',
 '459908786',
 '459908817',
 '459909728',
 '472464564',
 '459927619',
 '485022925',
 '485023009',
 '509152673',
 '472540391',
 '509153685',
 '472540404',
 '485024958',
 '485025728',
 '485028251',
 '485028699',
 '485038200',
 '526711598',
 '46267156',
 '509219314',
 '526713370',
 '46267172',
 '509223027',
 '526718450',
 '509227449',
 '526724867',
 '509230931',
 '509233505',
 '526739353',
 '526739609',
 '509247052',
 '526761913',
 '526762874',
 '564374168',
 '526778374',
 '526780159',
 '526785021',
 '526786076',
 '564418158',
 '564423130',
 '564423164',
 '548236645',
 '548247928',
 '564443362',
 '564443371',
 '564444716',
 '564446903',
 '564446921',
 '1305885941',
 '564448115',
 '564451198',
 '564451266',
 '564451770',
 '564452344',
 '564452415',
 '564455687',
 '585568467',
 '564456007',
 '585569279',
 '564460153',
 '564460219',
 '564460230',
 '564460234',
 '564461540',
 '802839251',
 '616623478',
 '585585406',
 '585585656',
 '585585734',
 '585585740',
 '585585744',
 '585585753',
 '585586220',
 '1464306945',
 '585586525',
 '585586551',
 '616632008',
 '585597674',
 '585600942',
 '616637255',
 '602699741',
 '602699782',
 '1464321217',
 '602717415',
 '602717444',
 '616640392',
 '602719477',
 '1174556810',
 '602720303',
 '602720383',
 '602720625',
 '616640877',
 '616640882',
 '616640885',
 '616640898',
 '616640903',
 '602720880',
 '602720889',
 '602720898',
 '616640914',
 '602720909',
 '602720923',
 '602720944',
 '602720955',
 '602720962',
 '616641005',
 '616642266',
 '616642876',
 '46287559',
 '46308007',
 '46308172',
 '46308717',
 '46309331',
 '46317115',
 '46337822',
 '46337970',
 '46367794',
 '46368073',
 '46372787',
 '46373227',
 '46373366',
 '46378206',
 '46379809',
 '46380013',
 '46394854',
 '46394861',
 '46395035',
 '46406583',
 '46406590',
 '46415925',
 '46415926',
 '46415933',
 '46421372',
 '46425984',
 '46426001',
 '46426012',
 '46484989',
 '46485586',
 '46485588',
 '46485592',
 '46485585',
 '46485597',
 '46485599',
 '46485602',
 '46500784',
 '46500770',
 '147156862',
 '46507148',
 '46507267',
 '46520972',
 '46532672',
 '46540411',
 '46544323',
 '46545528',
 '46559056',
 '46595058',
 '46595060',
 '46595063',
 '46595068',
 '46595072',
 '46595075',
 '46595077',
 '46595094',
 '46596057',
 '46603792',
 '46603786',
 '46603819',
 '46603985',
 '46604097',
 '46604092',
 '46604149',
 '46604320',
 '46604532',
 '46604625',
 '46604928',
 '46605254',
 '46605732',
 '46605805',
 '46605820',
 '46605938',
 '46606511',
 '46606650',
 '46608037',
 '46608193',
 '46608367',
 '46608420',
 '46608522',
 '46608554',
 '46608789',
 '46610117',
 '46610350',
 '46612793',
 '46616384',
 '46655259',
 '46655307',
 '46656359',
 '46658524',
 '46660377',
 '46661488',
 '46664002',
 '616698319',
 '616698727',
 '616698740',
 '616698762',
 '629621473',
 '629621478',
 '629621487',
 '629624988',
 '629624996',
 '629625010',
 '629625029',
 '629627031',
 '629627041',
 '629627043',
 '629627077',
 '629627190',
 '629627231',
 '629635662',
 '629635667',
 '629640586',
 '629640648',
 '652465846',
 '652466709',
 '652466725',
 '629649873',
 '629649876',
 '629649879',
 '629649894',
 '629654821',
 '1174637262',
 '652469199',
 '652469390',
 '652472421',
 '689315326',
 '678196157',
 '678196165',
 '678196225',
 '689315469',
 '689315489',
 '689315500',
 '678196237',
 '689315506',
 '689315516',
 '652479239',
 '689318119',
 '689318451',
 '689318454',
 '689318514',
 '689318515',
 '727535477',
 '740457192',
 '727535645',
 '774128063',
 '727535646',
 '727535647',
 '740457924',
 '46723888',
 '740479286',
 '740490603',
 '740490604',
 '740490681',
 '936913866',
 '774154686',
 '740492127',
 '754100963',
 '740501086',
 '754105253',
 '774174668',
 '774174679',
 '774174682',
 '774174755',
 '774174776',
 '774174782',
 '774174790',
 '774174796',
 '774174816',
 '774174828',
 '774175566',
 '774175571',
 '774175583',
 '774175608',
 '774175616',
 '774175627',
 '774178719',
 '774180765',
 '774180773',
 '774180781',
 '774180954',
 '774181620',
 '803001445',
 '803001455',
 '852519770',
 '833846947',
 '818105777',
 '915449235',
 '818112484',
 '976234412',
 '870990829',
 '852524813',
 '852524818',
 '818125939',
 '852525028',
 '852525029',
 '852525034',
 '852525479',
 '852525486',
 '852525520',
 '1225578118',
 '915498936',
 '870995860',
 '1464997803',
 '870996502',
 '870996623',
 '936928225',
 '870998910',
 '870998917',
 '870998928',
 '870999083',
 '936932037',
 '871002608',
 '871002836',
 '892211977',
 '915537868',
 '1107152775',
 '936934600',
 '936934618',
 '1243831084',
 '871003597',
 '871003603',
 '871003627',
 '871003631',
 '871003657',
 '915539113',
 '936935487',
 '936935514',
 '915549245',
 '1174648763',
 '936935755',
 '1465026636',
 '936935809',
 '936935817',
 '936935952',
 '871006765',
 '936935969',
 '915551466',
 '915554456',
 '936935981',
 '915559397',
 '1243831529',
 '1226014921',
 '936937344',
 '936937349',
 '1095728566',
 '936937396',
 '936937403',
 '936937447',
 '936937595',
 '936937745',
 '936937833',
 '915578309',
 '936937888',
 '936938234',
 '936938286',
 '936945748',
 '1095748416',
 '936946079',
 '936946086',
 '936946092',
 '936946184',
 '936946444',
 '936946845',
 '1095753029',
 '936947462',
 '936947469',
 '936948111',
 '936952949',
 '936953063',
 '936953918',
 '936954330',
 '936956037',
 '602811528',
 '46750776',
 '936956967',
 '46750826',
 '46751245',
 '936958550',
 '936959331',
 '936959339',
 '936959347',
 '936959972',
 '936963308',
 '936964626',
 '1095780113',
 '936968085',
 '936969863',
 '936969890',
 '936970077',
 '936970262',
 '936970270',
 '954717839',
 '936970566',
 '936970583',
 '936971078',
 '936971148',
 '936971169',
 '936971192',
 '936971283',
 '936971300',
 '936971310',
 '936971433',
 '936971443',
 '936972801',
 '936975758',
 '936975870',
 '1180754449',
 '1095799417',
 '936978931',
 '1095800696',
 '936983299',
 '936983337',
 '954722133',
 '976257614',
 '976257630',
 '976257638',
 '954731996',
 '954732013',
 '954732019',
 '954732029',
 '954732111',
 '976262730',
 '954732507',
 '954732587',
 '954733232',
 '954734444',
 '954735238',
 '976264360',
 '1095844853',
 '988645855',
 '1174657992',
 '988645868',
 '1152744023',
 '976265068',
 '988649856',
 '1025369404',
 '1025369411',
 '1095855661',
 '1095855909',
 '1025375659',
 '996354468',
 '1095859145',
 '1107185978',
 '1025412477',
 '1095862598',
 '1095862865',
 '1095863074',
 '1095863098',
 '1130435290',
 '996356040',
 '1130435838',
 '996361141',
 '1130437568',
 '1130438225',
 '1130438345',
 '1130438394',
 '1130439902',
 '1107190583',
 '1107190588',
 '1095889602',
 '1130442654',
 '1130451509',
 '1130452040',
 '1130452059',
 '1130452072',
 '1130452091',
 '1095896189',
 '1095898909',
 '1130452974',
 '1130452993',
 '1130453004',
 '1096088471',
 '1107198642',
 '1107198897',
 '1107198901',
 '1107201563',
 '1107203966',
 '1107206846',
 '1107208040',
 '1107213738',
 '1107217854',
 '1107217877',
 '1130463547',
 '1130463588',
 '1180805700',
 '1130468354',
 '1138258038',
 '1130469779',
 '46788778',
 '46788782',
 '46788817',
 '1138269335',
 '1130483057',
 '1152820499',
 '1163038182',
 '1152820752',
 '1163038200',
 '1152821171',
 '1152822096',
 '1174682041',
 '1174682143',
 '1174682152',
 '1152825404',
 '1152825543',
 '1163039035',
 '1152825982',
 '1152834143',
 '1163045900',
 '1174689983',
 '1174690716',
 '1163047053',
 '46797483',
 '46797474',
 '46797553',
 '1174695253',
 '46799140',
 '1163062123',
 '1163065018',
 '1180837360',
 '46803099',
 '1174705843',
 '1174705849',
 '1180841883',
 '1200903680',
 '1180846140',
 '1180846292',
 '1200904553',
 '1180853495',
 '1186757974',
 '1186758154',
 '46806595',
 '1180871774',
 '1200912887',
 '1180882612',
 '46807849',
 '46807959',
 '1180884804',
 '1186767028',
 '1180884810',
 '46808071',
 '46808088',
 '46808097',
 '46808146',
 '1180886756',
 '46808188',
 '46808922',
 '1186778564',
 '1186784547',
 '1186791420',
 '1200946038',
 '1200946192',
 '1200951671',
 '1397192117',
 '1206140088',
 '1206143500',
 '1220272284',
 '1208195273',
 '1217941594',
 '1220272630',
 '1217941597',
 '1217941613',
 '1217944535',
 '1217948496',
 '1217948513',
 '1217948581',
 '1217948592',
 '1217948603',
 '1217948613',
 '1226107839',
 '1217952719',
 '46813722',
 '46813738',
 '1264198855',
 '1220293238',
 '1264200395',
 '1235125703',
 '1235126096',
 '1220293306',
 '1220293309',
 '46821225',
 '1226211105',
 '1254345779',
 '1243967146',
 '1243967151',
 '1226211833',
 '1226211839',
 '1235127434',
 '1226219411',
 '1311349462',
 '1254347237',
 '1254347243',
 '1225578275',
 '1235142819',
 '1254348962',
 '1397217276',
 '1397217303',
 '1397217409',
 '1243976595',
 '1465254388',
 '1243981277',
 '1254350907',
 ...]

In [8]:
a = 0

a

0

In [9]:
crawler_status = 'error'

crawler_status

'error'

In [10]:
data = {'getArticleLinkedAllLinkingTargetManufacturer2': {'articleCountry': 'DE',
                                                          'articleId': input_.loc[a, 'Part Code'],
                                                          'country': 'DE',
                                                          'countryGroupFlag': False,
                                                          'linkingTargetType': 'VOLB',
                                                          'provider': 40_000}}

b = 0
while True:
    b += 1
    print(b)
    try:
        resp = requests.post('https://webservice.tecalliance.services/pegasus-3-0/services/TecdocToCatDLB.jsonEndpoint',
                             data=json.dumps(data),
                             headers=get_header(**{'x-api-key': key}),
                             #proxies=get_proxy(),
                             timeout=(10, 10))
            
        if resp.status_code == 200:
            json_ = resp.json()

            if json_['status'] == 401 and json_['statusText'].strip() == 'Access not allowed':
                while True:
                    try:
                        data = {'getAPIKeyForUser': {'catalog': 'tecdocsw',
                                                     'username': '186299u15',
                                                     'password': 'APMTeDoW14'}}
                        
                        resp = requests.post('https://webservice.tecalliance.services/webcat30/v1/services/WebCat30WS.jsonEndpoint',
                                             data=json.dumps(data),
                                             headers=get_header(),
                                             #proxies=get_proxy(),
                                             timeout=(10, 10))
                
                        if resp.status_code == 200:
                            json_ = resp.json()
                
                            if json_['status'] == 200:
                                key = json_['apiKey']
                                break
                    except KeyboardInterrupt:
                        break
                    except:
                        continue
            elif json_['status'] == 200:
                break
    except KeyboardInterrupt:
        break
    except:
        continue

resp

1

In [11]:
list_make = json_['data']['array']

list_make

[{'manuId': 104, 'manuName': 'SEAT'}, {'manuId': 121, 'manuName': 'VW'}]

In [12]:
len(list_make) == 0

False

In [13]:
list_make_code = [make['manuId'] for make in list_make]

list_make_code

[104, 121]

In [14]:
list_make = [make['manuName'].strip() for make in list_make]

list_make

['SEAT', 'VW']

In [16]:
df_temp = pd.DataFrame({'No': input_.loc[a, 'No'],
                        'Part Number': input_.loc[a, 'Part Number'],
                        'Part Code': input_.loc[a, 'Part Code'],
                        'Link Type': 'VOLB',
                        'Make No': [i+1 for i in range(len(list_make))],
                        'Make': list_make,
                        'Make Code': list_make_code})

output_correct = pd.concat([output_correct, df_temp], ignore_index=True).fillna('')

output_correct

   No Part Number Part Code Link Type  Make No  Make  Make Code
0   1       01101  44173537      VOLB        1  SEAT        104
1   1       01101  44173537      VOLB        2    VW        121

In [17]:
crawler_status = 'ok'

crawler_status

'ok'

In [18]:
if not output_correct.empty:
    output_correct = output_correct.sort_values(by=['No', 'Make No'],
                                                ascending=[True, True],
                                                ignore_index=True)
    output_correct.to_excel('./test_make.xlsx', index=False)

output_correct

   No Part Number Part Code Link Type  Make No  Make  Make Code
0   1       01101  44173537      VOLB        1  SEAT        104
1   1       01101  44173537      VOLB        2    VW        121

In [19]:
if crawler_status == 'error':
    output_error = pd.concat([output_error, pd.DataFrame([input_.iloc[a]]).reset_index(drop=True)], ignore_index=True).fillna('')

output_error

Empty DataFrame
Columns: []
Index: []

In [20]:
if not output_error.empty:
    output_error = output_error.sort_values(by=['No'],
                                            ascending=[True],
                                            ignore_index=True)
    output_error.to_excel('./test_make_error.xlsx', index=False)

output_error

Empty DataFrame
Columns: []
Index: []